export type ConnectorTemplate = {
  service: string;
  displayName: string;
  description: string;
  url: string;
  authType: "token" | "oauth";
  authLabel: string;
  authPlaceholder: string;
  guideSteps: string[];
  color: string;
  logoUrl: string;
  manifest?: string;         // optional copyable JSON manifest (e.g. Slack app manifest)
  manifestAfterStep?: number; // 0-based index of the step after which to show the manifest
};

export const CONNECTOR_TEMPLATES: ConnectorTemplate[] = [
  {
    service: "github",
    displayName: "GitHub",
    description: "Repositories, issues, PRs, and code search.",
    url: "https://api.githubcopilot.com/mcp/",
    authType: "token",
    authLabel: "Personal Access Token",
    authPlaceholder: "ghp_xxxxxxxxxxxxxxxxxxxx",
    guideSteps: [
      "Go to github.com/settings/tokens",
      "Click \"Generate new token (classic)\"",
      "Give it a name and select scopes (repo, issues, etc.)",
      "Click \"Generate token\" and copy it",
    ],
    color: "#E5E7EB",
    logoUrl: "https://cdn.simpleicons.org/github/white",
  },
  {
    service: "atlassian",
    displayName: "Atlassian",
    description: "Jira issues and Confluence pages via Rovo MCP.",
    url: "https://mcp.atlassian.com/v1/mcp",
    authType: "token",
    authLabel: "API Token",
    authPlaceholder: "ATATT3xFfGF0...",
    guideSteps: [
      "Make sure your org admin has enabled API token auth at support.atlassian.com/security-and-access-policies/docs/control-atlassian-rovo-mcp-server-settings",
      "Go to id.atlassian.com/manage-profile/security/api-tokens",
      "Click \"Create API token\", give it a label, and click \"Create\"",
      "Copy the token — it works for Jira, Confluence, and Compass",
    ],
    color: "#2684FF",
    logoUrl: "https://cdn.simpleicons.org/atlassian/2684FF",
  },
  {
    service: "slack",
    displayName: "Slack",
    description: "Channels, messages, and threads.",
    url: "https://mcp.slack.com/mcp",
    authType: "token",
    authLabel: "User Token",
    authPlaceholder: "xoxp-xxxxxxxxxxxx-xxxxxxxxxxxx",
    guideSteps: [
      "Go to api.slack.com/apps and click \"Create New App\"",
      "Choose \"From a manifest\", select your workspace, and paste the manifest below",
      "Click \"Create\", then go to \"Install App\" and install it to your workspace",
      "Go to Features → Agents & AI Apps and enable \"Model Context Protocol\"",
      "Copy the User OAuth Token from OAuth & Permissions (starts with xoxp-)",
    ],
    manifestAfterStep: 1,
    manifest: JSON.stringify({
      display_information: { name: "Komputer AI" },
      oauth_config: {
        scopes: {
          user: [
            "bookmarks:read",
            "bookmarks:write",
            "calls:read",
            "calls:write",
            "canvases:read",
            "canvases:write",
            "channels:history",
            "channels:read",
            "channels:write",
            "channels:write.invites",
            "channels:write.topic",
            "chat:write",
            "dnd:read",
            "dnd:write",
            "emoji:read",
            "files:read",
            "files:write",
            "groups:history",
            "groups:read",
            "groups:write",
            "groups:write.invites",
            "groups:write.topic",
            "im:history",
            "im:read",
            "im:write",
            "im:write.topic",
            "links:read",
            "links:write",
            "lists:read",
            "lists:write",
            "mpim:history",
            "mpim:read",
            "mpim:write",
            "mpim:write.topic",
            "pins:read",
            "pins:write",
            "reactions:read",
            "reactions:write",
            "reminders:read",
            "reminders:write",
            "remote_files:read",
            "remote_files:share",
            "search:read",
            "search:read.files",
            "search:read.im",
            "search:read.mpim",
            "search:read.private",
            "search:read.public",
            "search:read.users",
            "stars:read",
            "stars:write",
            "team:read",
            "team.preferences:read",
            "usergroups:read",
            "usergroups:write",
            "users.profile:read",
            "users.profile:write",
            "users:read",
            "users:read.email",
            "users:write",
          ],
        },
      },
      settings: { org_deploy_enabled: false, socket_mode_enabled: false, token_rotation_enabled: false },
    }, null, 2),
    color: "#E01E5A",
    logoUrl: "https://a.slack-edge.com/80588/marketing/img/icons/icon_slack_hash_colored.png",
  },
  {
    service: "gmail",
    displayName: "Gmail",
    description: "Read, search, and draft emails.",
    url: "",
    authType: "oauth",
    authLabel: "OAuth Credentials",
    authPlaceholder: "",
    guideSteps: [
      "Go to console.cloud.google.com/apis/credentials and create an OAuth 2.0 Client ID (type: Web application)",
      "Add your callback URL as an Authorized redirect URI (e.g. https://your-domain/api/v1/oauth/callback)",
      "Enable the Gmail API at console.cloud.google.com/apis/library/gmail.googleapis.com",
      "Copy the Client ID and Client Secret into the fields below, then click Connect",
    ],
    color: "#EA4335",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7e/Gmail_icon_%282020%29.svg",
  },
  {
    service: "google-calendar",
    displayName: "Google Calendar",
    description: "Events, schedules, and availability.",
    url: "",
    authType: "oauth",
    authLabel: "OAuth Credentials",
    authPlaceholder: "",
    guideSteps: [
      "Go to console.cloud.google.com/apis/credentials and create an OAuth 2.0 Client ID (type: Web application)",
      "Add your callback URL as an Authorized redirect URI (e.g. https://your-domain/api/v1/oauth/callback)",
      "Enable the Calendar API at console.cloud.google.com/apis/library/calendar-json.googleapis.com",
      "Copy the Client ID and Client Secret into the fields below, then click Connect",
    ],
    color: "#4285F4",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Google_Calendar_icon_%282020%29.svg",
  },
  {
    service: "linear",
    displayName: "Linear",
    description: "Issues, projects, and cycles.",
    url: "https://mcp.linear.app/mcp",
    authType: "token",
    authLabel: "API Key",
    authPlaceholder: "lin_api_xxxxxxxxxxxxxxxxxxxx",
    guideSteps: [
      "Go to linear.app/settings/account/security",
      "Scroll to \"API keys\" and click \"Create key\"",
      "Give it a label and copy the key",
    ],
    color: "#5E6AD2",
    logoUrl: "https://cdn.simpleicons.org/linear/5E6AD2",
  },
  {
    service: "notion",
    displayName: "Notion",
    description: "Pages, databases, and content.",
    url: "https://mcp.notion.com/mcp",
    authType: "oauth",
    authLabel: "OAuth Credentials",
    authPlaceholder: "",
    guideSteps: [
      "Go to notion.so/profile/integrations/public and click \"New integration\"",
      "Set the type to \"Public\" and fill in the redirect URI (e.g. https://your-domain/api/v1/oauth/callback)",
      "Under Capabilities, select the permissions your agents need (read content, update content, etc.)",
      "Copy the OAuth Client ID and Client Secret into the fields below, then click Connect",
    ],
    color: "#E5E7EB",
    logoUrl: "https://cdn.simpleicons.org/notion/white",
  },
  {
    service: "custom",
    displayName: "Custom",
    description: "Connect any MCP server by URL.",
    url: "__custom__",
    authType: "token",
    authLabel: "Auth Token",
    authPlaceholder: "",
    guideSteps: [],
    color: "#6B7280",
    logoUrl: "",
  },
];

export function getTemplateByService(service: string): ConnectorTemplate | undefined {
  return CONNECTOR_TEMPLATES.find((t) => t.service === service);
}
