/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1ResourceName the model 'V1ResourceName'
type V1ResourceName string

// List of v1.ResourceName
const (
	ResourceCPU V1ResourceName = "cpu"
	ResourceMemory V1ResourceName = "memory"
	ResourceStorage V1ResourceName = "storage"
	ResourceEphemeralStorage V1ResourceName = "ephemeral-storage"
	ResourcePods V1ResourceName = "pods"
	ResourceServices V1ResourceName = "services"
	ResourceReplicationControllers V1ResourceName = "replicationcontrollers"
	ResourceQuotas V1ResourceName = "resourcequotas"
	ResourceSecrets V1ResourceName = "secrets"
	ResourceConfigMaps V1ResourceName = "configmaps"
	ResourcePersistentVolumeClaims V1ResourceName = "persistentvolumeclaims"
	ResourceServicesNodePorts V1ResourceName = "services.nodeports"
	ResourceServicesLoadBalancers V1ResourceName = "services.loadbalancers"
	ResourceRequestsCPU V1ResourceName = "requests.cpu"
	ResourceRequestsMemory V1ResourceName = "requests.memory"
	ResourceRequestsStorage V1ResourceName = "requests.storage"
	ResourceRequestsEphemeralStorage V1ResourceName = "requests.ephemeral-storage"
	ResourceLimitsCPU V1ResourceName = "limits.cpu"
	ResourceLimitsMemory V1ResourceName = "limits.memory"
	ResourceLimitsEphemeralStorage V1ResourceName = "limits.ephemeral-storage"
)

// All allowed values of V1ResourceName enum
var AllowedV1ResourceNameEnumValues = []V1ResourceName{
	"cpu",
	"memory",
	"storage",
	"ephemeral-storage",
	"pods",
	"services",
	"replicationcontrollers",
	"resourcequotas",
	"secrets",
	"configmaps",
	"persistentvolumeclaims",
	"services.nodeports",
	"services.loadbalancers",
	"requests.cpu",
	"requests.memory",
	"requests.storage",
	"requests.ephemeral-storage",
	"limits.cpu",
	"limits.memory",
	"limits.ephemeral-storage",
}

func (v *V1ResourceName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1ResourceName(value)
	for _, existing := range AllowedV1ResourceNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1ResourceName", value)
}

// NewV1ResourceNameFromValue returns a pointer to a valid V1ResourceName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1ResourceNameFromValue(v string) (*V1ResourceName, error) {
	ev := V1ResourceName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1ResourceName: valid values are %v", v, AllowedV1ResourceNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1ResourceName) IsValid() bool {
	for _, existing := range AllowedV1ResourceNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.ResourceName value
func (v V1ResourceName) Ptr() *V1ResourceName {
	return &v
}

type NullableV1ResourceName struct {
	value *V1ResourceName
	isSet bool
}

func (v NullableV1ResourceName) Get() *V1ResourceName {
	return v.value
}

func (v *NullableV1ResourceName) Set(val *V1ResourceName) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ResourceName) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ResourceName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ResourceName(val *V1ResourceName) *NullableV1ResourceName {
	return &NullableV1ResourceName{value: val, isSet: true}
}

func (v NullableV1ResourceName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ResourceName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

