/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1RestartPolicy the model 'V1RestartPolicy'
type V1RestartPolicy string

// List of v1.RestartPolicy
const (
	RestartPolicyAlways V1RestartPolicy = "Always"
	RestartPolicyOnFailure V1RestartPolicy = "OnFailure"
	RestartPolicyNever V1RestartPolicy = "Never"
)

// All allowed values of V1RestartPolicy enum
var AllowedV1RestartPolicyEnumValues = []V1RestartPolicy{
	"Always",
	"OnFailure",
	"Never",
}

func (v *V1RestartPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1RestartPolicy(value)
	for _, existing := range AllowedV1RestartPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1RestartPolicy", value)
}

// NewV1RestartPolicyFromValue returns a pointer to a valid V1RestartPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1RestartPolicyFromValue(v string) (*V1RestartPolicy, error) {
	ev := V1RestartPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1RestartPolicy: valid values are %v", v, AllowedV1RestartPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1RestartPolicy) IsValid() bool {
	for _, existing := range AllowedV1RestartPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.RestartPolicy value
func (v V1RestartPolicy) Ptr() *V1RestartPolicy {
	return &v
}

type NullableV1RestartPolicy struct {
	value *V1RestartPolicy
	isSet bool
}

func (v NullableV1RestartPolicy) Get() *V1RestartPolicy {
	return v.value
}

func (v *NullableV1RestartPolicy) Set(val *V1RestartPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1RestartPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1RestartPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1RestartPolicy(val *V1RestartPolicy) *NullableV1RestartPolicy {
	return &NullableV1RestartPolicy{value: val, isSet: true}
}

func (v NullableV1RestartPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1RestartPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

