/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1PullPolicy the model 'V1PullPolicy'
type V1PullPolicy string

// List of v1.PullPolicy
const (
	PullAlways V1PullPolicy = "Always"
	PullNever V1PullPolicy = "Never"
	PullIfNotPresent V1PullPolicy = "IfNotPresent"
)

// All allowed values of V1PullPolicy enum
var AllowedV1PullPolicyEnumValues = []V1PullPolicy{
	"Always",
	"Never",
	"IfNotPresent",
}

func (v *V1PullPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1PullPolicy(value)
	for _, existing := range AllowedV1PullPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1PullPolicy", value)
}

// NewV1PullPolicyFromValue returns a pointer to a valid V1PullPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1PullPolicyFromValue(v string) (*V1PullPolicy, error) {
	ev := V1PullPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1PullPolicy: valid values are %v", v, AllowedV1PullPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1PullPolicy) IsValid() bool {
	for _, existing := range AllowedV1PullPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.PullPolicy value
func (v V1PullPolicy) Ptr() *V1PullPolicy {
	return &v
}

type NullableV1PullPolicy struct {
	value *V1PullPolicy
	isSet bool
}

func (v NullableV1PullPolicy) Get() *V1PullPolicy {
	return v.value
}

func (v *NullableV1PullPolicy) Set(val *V1PullPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PullPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PullPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PullPolicy(val *V1PullPolicy) *NullableV1PullPolicy {
	return &NullableV1PullPolicy{value: val, isSet: true}
}

func (v NullableV1PullPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PullPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

