/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the AgentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentResponse{}

// AgentResponse struct for AgentResponse
type AgentResponse struct {
	// KomputerConnector names attached to this agent
	Connectors []string `json:"connectors,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	// User task (spec.instructions)
	Instructions *string `json:"instructions,omitempty"`
	LastTaskCostUSD *string `json:"lastTaskCostUSD,omitempty"`
	LastTaskMessage *string `json:"lastTaskMessage,omitempty"`
	Lifecycle *string `json:"lifecycle,omitempty"`
	// KomputerMemory names attached to this agent
	Memories []string `json:"memories,omitempty"`
	Model *string `json:"model,omitempty"`
	ModelContextWindow *int32 `json:"modelContextWindow,omitempty"`
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	// Key names from K8s Secrets (not values)
	Secrets []string `json:"secrets,omitempty"`
	// KomputerSkill names attached to this agent
	Skills []string `json:"skills,omitempty"`
	Status *string `json:"status,omitempty"`
	// Custom system prompt (spec.systemPrompt)
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	TaskStatus *string `json:"taskStatus,omitempty"`
	TotalCostUSD *string `json:"totalCostUSD,omitempty"`
	TotalTokens *int32 `json:"totalTokens,omitempty"`
}

// NewAgentResponse instantiates a new AgentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentResponse() *AgentResponse {
	this := AgentResponse{}
	return &this
}

// NewAgentResponseWithDefaults instantiates a new AgentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentResponseWithDefaults() *AgentResponse {
	this := AgentResponse{}
	return &this
}

// GetConnectors returns the Connectors field value if set, zero value otherwise.
func (o *AgentResponse) GetConnectors() []string {
	if o == nil || IsNil(o.Connectors) {
		var ret []string
		return ret
	}
	return o.Connectors
}

// GetConnectorsOk returns a tuple with the Connectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetConnectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Connectors) {
		return nil, false
	}
	return o.Connectors, true
}

// HasConnectors returns a boolean if a field has been set.
func (o *AgentResponse) HasConnectors() bool {
	if o != nil && !IsNil(o.Connectors) {
		return true
	}

	return false
}

// SetConnectors gets a reference to the given []string and assigns it to the Connectors field.
func (o *AgentResponse) SetConnectors(v []string) {
	o.Connectors = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *AgentResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *AgentResponse) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *AgentResponse) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *AgentResponse) SetInstructions(v string) {
	o.Instructions = &v
}

// GetLastTaskCostUSD returns the LastTaskCostUSD field value if set, zero value otherwise.
func (o *AgentResponse) GetLastTaskCostUSD() string {
	if o == nil || IsNil(o.LastTaskCostUSD) {
		var ret string
		return ret
	}
	return *o.LastTaskCostUSD
}

// GetLastTaskCostUSDOk returns a tuple with the LastTaskCostUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetLastTaskCostUSDOk() (*string, bool) {
	if o == nil || IsNil(o.LastTaskCostUSD) {
		return nil, false
	}
	return o.LastTaskCostUSD, true
}

// HasLastTaskCostUSD returns a boolean if a field has been set.
func (o *AgentResponse) HasLastTaskCostUSD() bool {
	if o != nil && !IsNil(o.LastTaskCostUSD) {
		return true
	}

	return false
}

// SetLastTaskCostUSD gets a reference to the given string and assigns it to the LastTaskCostUSD field.
func (o *AgentResponse) SetLastTaskCostUSD(v string) {
	o.LastTaskCostUSD = &v
}

// GetLastTaskMessage returns the LastTaskMessage field value if set, zero value otherwise.
func (o *AgentResponse) GetLastTaskMessage() string {
	if o == nil || IsNil(o.LastTaskMessage) {
		var ret string
		return ret
	}
	return *o.LastTaskMessage
}

// GetLastTaskMessageOk returns a tuple with the LastTaskMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetLastTaskMessageOk() (*string, bool) {
	if o == nil || IsNil(o.LastTaskMessage) {
		return nil, false
	}
	return o.LastTaskMessage, true
}

// HasLastTaskMessage returns a boolean if a field has been set.
func (o *AgentResponse) HasLastTaskMessage() bool {
	if o != nil && !IsNil(o.LastTaskMessage) {
		return true
	}

	return false
}

// SetLastTaskMessage gets a reference to the given string and assigns it to the LastTaskMessage field.
func (o *AgentResponse) SetLastTaskMessage(v string) {
	o.LastTaskMessage = &v
}

// GetLifecycle returns the Lifecycle field value if set, zero value otherwise.
func (o *AgentResponse) GetLifecycle() string {
	if o == nil || IsNil(o.Lifecycle) {
		var ret string
		return ret
	}
	return *o.Lifecycle
}

// GetLifecycleOk returns a tuple with the Lifecycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetLifecycleOk() (*string, bool) {
	if o == nil || IsNil(o.Lifecycle) {
		return nil, false
	}
	return o.Lifecycle, true
}

// HasLifecycle returns a boolean if a field has been set.
func (o *AgentResponse) HasLifecycle() bool {
	if o != nil && !IsNil(o.Lifecycle) {
		return true
	}

	return false
}

// SetLifecycle gets a reference to the given string and assigns it to the Lifecycle field.
func (o *AgentResponse) SetLifecycle(v string) {
	o.Lifecycle = &v
}

// GetMemories returns the Memories field value if set, zero value otherwise.
func (o *AgentResponse) GetMemories() []string {
	if o == nil || IsNil(o.Memories) {
		var ret []string
		return ret
	}
	return o.Memories
}

// GetMemoriesOk returns a tuple with the Memories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetMemoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Memories) {
		return nil, false
	}
	return o.Memories, true
}

// HasMemories returns a boolean if a field has been set.
func (o *AgentResponse) HasMemories() bool {
	if o != nil && !IsNil(o.Memories) {
		return true
	}

	return false
}

// SetMemories gets a reference to the given []string and assigns it to the Memories field.
func (o *AgentResponse) SetMemories(v []string) {
	o.Memories = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *AgentResponse) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *AgentResponse) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *AgentResponse) SetModel(v string) {
	o.Model = &v
}

// GetModelContextWindow returns the ModelContextWindow field value if set, zero value otherwise.
func (o *AgentResponse) GetModelContextWindow() int32 {
	if o == nil || IsNil(o.ModelContextWindow) {
		var ret int32
		return ret
	}
	return *o.ModelContextWindow
}

// GetModelContextWindowOk returns a tuple with the ModelContextWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetModelContextWindowOk() (*int32, bool) {
	if o == nil || IsNil(o.ModelContextWindow) {
		return nil, false
	}
	return o.ModelContextWindow, true
}

// HasModelContextWindow returns a boolean if a field has been set.
func (o *AgentResponse) HasModelContextWindow() bool {
	if o != nil && !IsNil(o.ModelContextWindow) {
		return true
	}

	return false
}

// SetModelContextWindow gets a reference to the given int32 and assigns it to the ModelContextWindow field.
func (o *AgentResponse) SetModelContextWindow(v int32) {
	o.ModelContextWindow = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentResponse) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AgentResponse) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AgentResponse) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AgentResponse) SetNamespace(v string) {
	o.Namespace = &v
}

// GetSecrets returns the Secrets field value if set, zero value otherwise.
func (o *AgentResponse) GetSecrets() []string {
	if o == nil || IsNil(o.Secrets) {
		var ret []string
		return ret
	}
	return o.Secrets
}

// GetSecretsOk returns a tuple with the Secrets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetSecretsOk() ([]string, bool) {
	if o == nil || IsNil(o.Secrets) {
		return nil, false
	}
	return o.Secrets, true
}

// HasSecrets returns a boolean if a field has been set.
func (o *AgentResponse) HasSecrets() bool {
	if o != nil && !IsNil(o.Secrets) {
		return true
	}

	return false
}

// SetSecrets gets a reference to the given []string and assigns it to the Secrets field.
func (o *AgentResponse) SetSecrets(v []string) {
	o.Secrets = v
}

// GetSkills returns the Skills field value if set, zero value otherwise.
func (o *AgentResponse) GetSkills() []string {
	if o == nil || IsNil(o.Skills) {
		var ret []string
		return ret
	}
	return o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetSkillsOk() ([]string, bool) {
	if o == nil || IsNil(o.Skills) {
		return nil, false
	}
	return o.Skills, true
}

// HasSkills returns a boolean if a field has been set.
func (o *AgentResponse) HasSkills() bool {
	if o != nil && !IsNil(o.Skills) {
		return true
	}

	return false
}

// SetSkills gets a reference to the given []string and assigns it to the Skills field.
func (o *AgentResponse) SetSkills(v []string) {
	o.Skills = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *AgentResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *AgentResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *AgentResponse) SetStatus(v string) {
	o.Status = &v
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise.
func (o *AgentResponse) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt) {
		var ret string
		return ret
	}
	return *o.SystemPrompt
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetSystemPromptOk() (*string, bool) {
	if o == nil || IsNil(o.SystemPrompt) {
		return nil, false
	}
	return o.SystemPrompt, true
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *AgentResponse) HasSystemPrompt() bool {
	if o != nil && !IsNil(o.SystemPrompt) {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given string and assigns it to the SystemPrompt field.
func (o *AgentResponse) SetSystemPrompt(v string) {
	o.SystemPrompt = &v
}

// GetTaskStatus returns the TaskStatus field value if set, zero value otherwise.
func (o *AgentResponse) GetTaskStatus() string {
	if o == nil || IsNil(o.TaskStatus) {
		var ret string
		return ret
	}
	return *o.TaskStatus
}

// GetTaskStatusOk returns a tuple with the TaskStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTaskStatusOk() (*string, bool) {
	if o == nil || IsNil(o.TaskStatus) {
		return nil, false
	}
	return o.TaskStatus, true
}

// HasTaskStatus returns a boolean if a field has been set.
func (o *AgentResponse) HasTaskStatus() bool {
	if o != nil && !IsNil(o.TaskStatus) {
		return true
	}

	return false
}

// SetTaskStatus gets a reference to the given string and assigns it to the TaskStatus field.
func (o *AgentResponse) SetTaskStatus(v string) {
	o.TaskStatus = &v
}

// GetTotalCostUSD returns the TotalCostUSD field value if set, zero value otherwise.
func (o *AgentResponse) GetTotalCostUSD() string {
	if o == nil || IsNil(o.TotalCostUSD) {
		var ret string
		return ret
	}
	return *o.TotalCostUSD
}

// GetTotalCostUSDOk returns a tuple with the TotalCostUSD field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTotalCostUSDOk() (*string, bool) {
	if o == nil || IsNil(o.TotalCostUSD) {
		return nil, false
	}
	return o.TotalCostUSD, true
}

// HasTotalCostUSD returns a boolean if a field has been set.
func (o *AgentResponse) HasTotalCostUSD() bool {
	if o != nil && !IsNil(o.TotalCostUSD) {
		return true
	}

	return false
}

// SetTotalCostUSD gets a reference to the given string and assigns it to the TotalCostUSD field.
func (o *AgentResponse) SetTotalCostUSD(v string) {
	o.TotalCostUSD = &v
}

// GetTotalTokens returns the TotalTokens field value if set, zero value otherwise.
func (o *AgentResponse) GetTotalTokens() int32 {
	if o == nil || IsNil(o.TotalTokens) {
		var ret int32
		return ret
	}
	return *o.TotalTokens
}

// GetTotalTokensOk returns a tuple with the TotalTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentResponse) GetTotalTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTokens) {
		return nil, false
	}
	return o.TotalTokens, true
}

// HasTotalTokens returns a boolean if a field has been set.
func (o *AgentResponse) HasTotalTokens() bool {
	if o != nil && !IsNil(o.TotalTokens) {
		return true
	}

	return false
}

// SetTotalTokens gets a reference to the given int32 and assigns it to the TotalTokens field.
func (o *AgentResponse) SetTotalTokens(v int32) {
	o.TotalTokens = &v
}

func (o AgentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connectors) {
		toSerialize["connectors"] = o.Connectors
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.LastTaskCostUSD) {
		toSerialize["lastTaskCostUSD"] = o.LastTaskCostUSD
	}
	if !IsNil(o.LastTaskMessage) {
		toSerialize["lastTaskMessage"] = o.LastTaskMessage
	}
	if !IsNil(o.Lifecycle) {
		toSerialize["lifecycle"] = o.Lifecycle
	}
	if !IsNil(o.Memories) {
		toSerialize["memories"] = o.Memories
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	if !IsNil(o.ModelContextWindow) {
		toSerialize["modelContextWindow"] = o.ModelContextWindow
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Secrets) {
		toSerialize["secrets"] = o.Secrets
	}
	if !IsNil(o.Skills) {
		toSerialize["skills"] = o.Skills
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.SystemPrompt) {
		toSerialize["systemPrompt"] = o.SystemPrompt
	}
	if !IsNil(o.TaskStatus) {
		toSerialize["taskStatus"] = o.TaskStatus
	}
	if !IsNil(o.TotalCostUSD) {
		toSerialize["totalCostUSD"] = o.TotalCostUSD
	}
	if !IsNil(o.TotalTokens) {
		toSerialize["totalTokens"] = o.TotalTokens
	}
	return toSerialize, nil
}

type NullableAgentResponse struct {
	value *AgentResponse
	isSet bool
}

func (v NullableAgentResponse) Get() *AgentResponse {
	return v.value
}

func (v *NullableAgentResponse) Set(val *AgentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentResponse(val *AgentResponse) *NullableAgentResponse {
	return &NullableAgentResponse{value: val, isSet: true}
}

func (v NullableAgentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


