/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1NodeInclusionPolicy the model 'V1NodeInclusionPolicy'
type V1NodeInclusionPolicy string

// List of v1.NodeInclusionPolicy
const (
	NodeInclusionPolicyIgnore V1NodeInclusionPolicy = "Ignore"
	NodeInclusionPolicyHonor V1NodeInclusionPolicy = "Honor"
)

// All allowed values of V1NodeInclusionPolicy enum
var AllowedV1NodeInclusionPolicyEnumValues = []V1NodeInclusionPolicy{
	"Ignore",
	"Honor",
}

func (v *V1NodeInclusionPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1NodeInclusionPolicy(value)
	for _, existing := range AllowedV1NodeInclusionPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1NodeInclusionPolicy", value)
}

// NewV1NodeInclusionPolicyFromValue returns a pointer to a valid V1NodeInclusionPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1NodeInclusionPolicyFromValue(v string) (*V1NodeInclusionPolicy, error) {
	ev := V1NodeInclusionPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1NodeInclusionPolicy: valid values are %v", v, AllowedV1NodeInclusionPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1NodeInclusionPolicy) IsValid() bool {
	for _, existing := range AllowedV1NodeInclusionPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.NodeInclusionPolicy value
func (v V1NodeInclusionPolicy) Ptr() *V1NodeInclusionPolicy {
	return &v
}

type NullableV1NodeInclusionPolicy struct {
	value *V1NodeInclusionPolicy
	isSet bool
}

func (v NullableV1NodeInclusionPolicy) Get() *V1NodeInclusionPolicy {
	return v.value
}

func (v *NullableV1NodeInclusionPolicy) Set(val *V1NodeInclusionPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1NodeInclusionPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1NodeInclusionPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1NodeInclusionPolicy(val *V1NodeInclusionPolicy) *NullableV1NodeInclusionPolicy {
	return &NullableV1NodeInclusionPolicy{value: val, isSet: true}
}

func (v NullableV1NodeInclusionPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1NodeInclusionPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

