/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the ConnectorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectorResponse{}

// ConnectorResponse struct for ConnectorResponse
type ConnectorResponse struct {
	AgentNames []string `json:"agentNames,omitempty"`
	AttachedAgents *int32 `json:"attachedAgents,omitempty"`
	AuthSecretKey *string `json:"authSecretKey,omitempty"`
	AuthSecretName *string `json:"authSecretName,omitempty"`
	AuthType *string `json:"authType,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	Name *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	// \"pending\", \"connected\", \"\"
	OauthStatus *string `json:"oauthStatus,omitempty"`
	Service *string `json:"service,omitempty"`
	Type *string `json:"type,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewConnectorResponse instantiates a new ConnectorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorResponse() *ConnectorResponse {
	this := ConnectorResponse{}
	return &this
}

// NewConnectorResponseWithDefaults instantiates a new ConnectorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorResponseWithDefaults() *ConnectorResponse {
	this := ConnectorResponse{}
	return &this
}

// GetAgentNames returns the AgentNames field value if set, zero value otherwise.
func (o *ConnectorResponse) GetAgentNames() []string {
	if o == nil || IsNil(o.AgentNames) {
		var ret []string
		return ret
	}
	return o.AgentNames
}

// GetAgentNamesOk returns a tuple with the AgentNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetAgentNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.AgentNames) {
		return nil, false
	}
	return o.AgentNames, true
}

// HasAgentNames returns a boolean if a field has been set.
func (o *ConnectorResponse) HasAgentNames() bool {
	if o != nil && !IsNil(o.AgentNames) {
		return true
	}

	return false
}

// SetAgentNames gets a reference to the given []string and assigns it to the AgentNames field.
func (o *ConnectorResponse) SetAgentNames(v []string) {
	o.AgentNames = v
}

// GetAttachedAgents returns the AttachedAgents field value if set, zero value otherwise.
func (o *ConnectorResponse) GetAttachedAgents() int32 {
	if o == nil || IsNil(o.AttachedAgents) {
		var ret int32
		return ret
	}
	return *o.AttachedAgents
}

// GetAttachedAgentsOk returns a tuple with the AttachedAgents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetAttachedAgentsOk() (*int32, bool) {
	if o == nil || IsNil(o.AttachedAgents) {
		return nil, false
	}
	return o.AttachedAgents, true
}

// HasAttachedAgents returns a boolean if a field has been set.
func (o *ConnectorResponse) HasAttachedAgents() bool {
	if o != nil && !IsNil(o.AttachedAgents) {
		return true
	}

	return false
}

// SetAttachedAgents gets a reference to the given int32 and assigns it to the AttachedAgents field.
func (o *ConnectorResponse) SetAttachedAgents(v int32) {
	o.AttachedAgents = &v
}

// GetAuthSecretKey returns the AuthSecretKey field value if set, zero value otherwise.
func (o *ConnectorResponse) GetAuthSecretKey() string {
	if o == nil || IsNil(o.AuthSecretKey) {
		var ret string
		return ret
	}
	return *o.AuthSecretKey
}

// GetAuthSecretKeyOk returns a tuple with the AuthSecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetAuthSecretKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AuthSecretKey) {
		return nil, false
	}
	return o.AuthSecretKey, true
}

// HasAuthSecretKey returns a boolean if a field has been set.
func (o *ConnectorResponse) HasAuthSecretKey() bool {
	if o != nil && !IsNil(o.AuthSecretKey) {
		return true
	}

	return false
}

// SetAuthSecretKey gets a reference to the given string and assigns it to the AuthSecretKey field.
func (o *ConnectorResponse) SetAuthSecretKey(v string) {
	o.AuthSecretKey = &v
}

// GetAuthSecretName returns the AuthSecretName field value if set, zero value otherwise.
func (o *ConnectorResponse) GetAuthSecretName() string {
	if o == nil || IsNil(o.AuthSecretName) {
		var ret string
		return ret
	}
	return *o.AuthSecretName
}

// GetAuthSecretNameOk returns a tuple with the AuthSecretName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetAuthSecretNameOk() (*string, bool) {
	if o == nil || IsNil(o.AuthSecretName) {
		return nil, false
	}
	return o.AuthSecretName, true
}

// HasAuthSecretName returns a boolean if a field has been set.
func (o *ConnectorResponse) HasAuthSecretName() bool {
	if o != nil && !IsNil(o.AuthSecretName) {
		return true
	}

	return false
}

// SetAuthSecretName gets a reference to the given string and assigns it to the AuthSecretName field.
func (o *ConnectorResponse) SetAuthSecretName(v string) {
	o.AuthSecretName = &v
}

// GetAuthType returns the AuthType field value if set, zero value otherwise.
func (o *ConnectorResponse) GetAuthType() string {
	if o == nil || IsNil(o.AuthType) {
		var ret string
		return ret
	}
	return *o.AuthType
}

// GetAuthTypeOk returns a tuple with the AuthType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetAuthTypeOk() (*string, bool) {
	if o == nil || IsNil(o.AuthType) {
		return nil, false
	}
	return o.AuthType, true
}

// HasAuthType returns a boolean if a field has been set.
func (o *ConnectorResponse) HasAuthType() bool {
	if o != nil && !IsNil(o.AuthType) {
		return true
	}

	return false
}

// SetAuthType gets a reference to the given string and assigns it to the AuthType field.
func (o *ConnectorResponse) SetAuthType(v string) {
	o.AuthType = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ConnectorResponse) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ConnectorResponse) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ConnectorResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ConnectorResponse) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ConnectorResponse) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ConnectorResponse) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ConnectorResponse) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ConnectorResponse) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ConnectorResponse) SetName(v string) {
	o.Name = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ConnectorResponse) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ConnectorResponse) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ConnectorResponse) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOauthStatus returns the OauthStatus field value if set, zero value otherwise.
func (o *ConnectorResponse) GetOauthStatus() string {
	if o == nil || IsNil(o.OauthStatus) {
		var ret string
		return ret
	}
	return *o.OauthStatus
}

// GetOauthStatusOk returns a tuple with the OauthStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetOauthStatusOk() (*string, bool) {
	if o == nil || IsNil(o.OauthStatus) {
		return nil, false
	}
	return o.OauthStatus, true
}

// HasOauthStatus returns a boolean if a field has been set.
func (o *ConnectorResponse) HasOauthStatus() bool {
	if o != nil && !IsNil(o.OauthStatus) {
		return true
	}

	return false
}

// SetOauthStatus gets a reference to the given string and assigns it to the OauthStatus field.
func (o *ConnectorResponse) SetOauthStatus(v string) {
	o.OauthStatus = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *ConnectorResponse) GetService() string {
	if o == nil || IsNil(o.Service) {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetServiceOk() (*string, bool) {
	if o == nil || IsNil(o.Service) {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *ConnectorResponse) HasService() bool {
	if o != nil && !IsNil(o.Service) {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *ConnectorResponse) SetService(v string) {
	o.Service = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ConnectorResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ConnectorResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ConnectorResponse) SetType(v string) {
	o.Type = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ConnectorResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ConnectorResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ConnectorResponse) SetUrl(v string) {
	o.Url = &v
}

func (o ConnectorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentNames) {
		toSerialize["agentNames"] = o.AgentNames
	}
	if !IsNil(o.AttachedAgents) {
		toSerialize["attachedAgents"] = o.AttachedAgents
	}
	if !IsNil(o.AuthSecretKey) {
		toSerialize["authSecretKey"] = o.AuthSecretKey
	}
	if !IsNil(o.AuthSecretName) {
		toSerialize["authSecretName"] = o.AuthSecretName
	}
	if !IsNil(o.AuthType) {
		toSerialize["authType"] = o.AuthType
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.OauthStatus) {
		toSerialize["oauthStatus"] = o.OauthStatus
	}
	if !IsNil(o.Service) {
		toSerialize["service"] = o.Service
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableConnectorResponse struct {
	value *ConnectorResponse
	isSet bool
}

func (v NullableConnectorResponse) Get() *ConnectorResponse {
	return v.value
}

func (v *NullableConnectorResponse) Set(val *ConnectorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorResponse(val *ConnectorResponse) *NullableConnectorResponse {
	return &NullableConnectorResponse{value: val, isSet: true}
}

func (v NullableConnectorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


