/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the IntstrIntOrString type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntstrIntOrString{}

// IntstrIntOrString struct for IntstrIntOrString
type IntstrIntOrString struct {
	IntVal *int32 `json:"intVal,omitempty"`
	StrVal *string `json:"strVal,omitempty"`
	Type *IntstrType `json:"type,omitempty"`
}

// NewIntstrIntOrString instantiates a new IntstrIntOrString object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntstrIntOrString() *IntstrIntOrString {
	this := IntstrIntOrString{}
	return &this
}

// NewIntstrIntOrStringWithDefaults instantiates a new IntstrIntOrString object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntstrIntOrStringWithDefaults() *IntstrIntOrString {
	this := IntstrIntOrString{}
	return &this
}

// GetIntVal returns the IntVal field value if set, zero value otherwise.
func (o *IntstrIntOrString) GetIntVal() int32 {
	if o == nil || IsNil(o.IntVal) {
		var ret int32
		return ret
	}
	return *o.IntVal
}

// GetIntValOk returns a tuple with the IntVal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntstrIntOrString) GetIntValOk() (*int32, bool) {
	if o == nil || IsNil(o.IntVal) {
		return nil, false
	}
	return o.IntVal, true
}

// HasIntVal returns a boolean if a field has been set.
func (o *IntstrIntOrString) HasIntVal() bool {
	if o != nil && !IsNil(o.IntVal) {
		return true
	}

	return false
}

// SetIntVal gets a reference to the given int32 and assigns it to the IntVal field.
func (o *IntstrIntOrString) SetIntVal(v int32) {
	o.IntVal = &v
}

// GetStrVal returns the StrVal field value if set, zero value otherwise.
func (o *IntstrIntOrString) GetStrVal() string {
	if o == nil || IsNil(o.StrVal) {
		var ret string
		return ret
	}
	return *o.StrVal
}

// GetStrValOk returns a tuple with the StrVal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntstrIntOrString) GetStrValOk() (*string, bool) {
	if o == nil || IsNil(o.StrVal) {
		return nil, false
	}
	return o.StrVal, true
}

// HasStrVal returns a boolean if a field has been set.
func (o *IntstrIntOrString) HasStrVal() bool {
	if o != nil && !IsNil(o.StrVal) {
		return true
	}

	return false
}

// SetStrVal gets a reference to the given string and assigns it to the StrVal field.
func (o *IntstrIntOrString) SetStrVal(v string) {
	o.StrVal = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *IntstrIntOrString) GetType() IntstrType {
	if o == nil || IsNil(o.Type) {
		var ret IntstrType
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntstrIntOrString) GetTypeOk() (*IntstrType, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *IntstrIntOrString) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given IntstrType and assigns it to the Type field.
func (o *IntstrIntOrString) SetType(v IntstrType) {
	o.Type = &v
}

func (o IntstrIntOrString) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntstrIntOrString) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IntVal) {
		toSerialize["intVal"] = o.IntVal
	}
	if !IsNil(o.StrVal) {
		toSerialize["strVal"] = o.StrVal
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableIntstrIntOrString struct {
	value *IntstrIntOrString
	isSet bool
}

func (v NullableIntstrIntOrString) Get() *IntstrIntOrString {
	return v.value
}

func (v *NullableIntstrIntOrString) Set(val *IntstrIntOrString) {
	v.value = val
	v.isSet = true
}

func (v NullableIntstrIntOrString) IsSet() bool {
	return v.isSet
}

func (v *NullableIntstrIntOrString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntstrIntOrString(val *IntstrIntOrString) *NullableIntstrIntOrString {
	return &NullableIntstrIntOrString{value: val, isSet: true}
}

func (v NullableIntstrIntOrString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntstrIntOrString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


