/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1LabelSelectorOperator the model 'V1LabelSelectorOperator'
type V1LabelSelectorOperator string

// List of v1.LabelSelectorOperator
const (
	LabelSelectorOpIn V1LabelSelectorOperator = "In"
	LabelSelectorOpNotIn V1LabelSelectorOperator = "NotIn"
	LabelSelectorOpExists V1LabelSelectorOperator = "Exists"
	LabelSelectorOpDoesNotExist V1LabelSelectorOperator = "DoesNotExist"
)

// All allowed values of V1LabelSelectorOperator enum
var AllowedV1LabelSelectorOperatorEnumValues = []V1LabelSelectorOperator{
	"In",
	"NotIn",
	"Exists",
	"DoesNotExist",
}

func (v *V1LabelSelectorOperator) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1LabelSelectorOperator(value)
	for _, existing := range AllowedV1LabelSelectorOperatorEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1LabelSelectorOperator", value)
}

// NewV1LabelSelectorOperatorFromValue returns a pointer to a valid V1LabelSelectorOperator
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1LabelSelectorOperatorFromValue(v string) (*V1LabelSelectorOperator, error) {
	ev := V1LabelSelectorOperator(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1LabelSelectorOperator: valid values are %v", v, AllowedV1LabelSelectorOperatorEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1LabelSelectorOperator) IsValid() bool {
	for _, existing := range AllowedV1LabelSelectorOperatorEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.LabelSelectorOperator value
func (v V1LabelSelectorOperator) Ptr() *V1LabelSelectorOperator {
	return &v
}

type NullableV1LabelSelectorOperator struct {
	value *V1LabelSelectorOperator
	isSet bool
}

func (v NullableV1LabelSelectorOperator) Get() *V1LabelSelectorOperator {
	return v.value
}

func (v *NullableV1LabelSelectorOperator) Set(val *V1LabelSelectorOperator) {
	v.value = val
	v.isSet = true
}

func (v NullableV1LabelSelectorOperator) IsSet() bool {
	return v.isSet
}

func (v *NullableV1LabelSelectorOperator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1LabelSelectorOperator(val *V1LabelSelectorOperator) *NullableV1LabelSelectorOperator {
	return &NullableV1LabelSelectorOperator{value: val, isSet: true}
}

func (v NullableV1LabelSelectorOperator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1LabelSelectorOperator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

