/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1PodSELinuxChangePolicy the model 'V1PodSELinuxChangePolicy'
type V1PodSELinuxChangePolicy string

// List of v1.PodSELinuxChangePolicy
const (
	SELinuxChangePolicyRecursive V1PodSELinuxChangePolicy = "Recursive"
	SELinuxChangePolicyMountOption V1PodSELinuxChangePolicy = "MountOption"
)

// All allowed values of V1PodSELinuxChangePolicy enum
var AllowedV1PodSELinuxChangePolicyEnumValues = []V1PodSELinuxChangePolicy{
	"Recursive",
	"MountOption",
}

func (v *V1PodSELinuxChangePolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1PodSELinuxChangePolicy(value)
	for _, existing := range AllowedV1PodSELinuxChangePolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1PodSELinuxChangePolicy", value)
}

// NewV1PodSELinuxChangePolicyFromValue returns a pointer to a valid V1PodSELinuxChangePolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1PodSELinuxChangePolicyFromValue(v string) (*V1PodSELinuxChangePolicy, error) {
	ev := V1PodSELinuxChangePolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1PodSELinuxChangePolicy: valid values are %v", v, AllowedV1PodSELinuxChangePolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1PodSELinuxChangePolicy) IsValid() bool {
	for _, existing := range AllowedV1PodSELinuxChangePolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.PodSELinuxChangePolicy value
func (v V1PodSELinuxChangePolicy) Ptr() *V1PodSELinuxChangePolicy {
	return &v
}

type NullableV1PodSELinuxChangePolicy struct {
	value *V1PodSELinuxChangePolicy
	isSet bool
}

func (v NullableV1PodSELinuxChangePolicy) Get() *V1PodSELinuxChangePolicy {
	return v.value
}

func (v *NullableV1PodSELinuxChangePolicy) Set(val *V1PodSELinuxChangePolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PodSELinuxChangePolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PodSELinuxChangePolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PodSELinuxChangePolicy(val *V1PodSELinuxChangePolicy) *NullableV1PodSELinuxChangePolicy {
	return &NullableV1PodSELinuxChangePolicy{value: val, isSet: true}
}

func (v NullableV1PodSELinuxChangePolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PodSELinuxChangePolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

