/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"fmt"
)

// V1PreemptionPolicy the model 'V1PreemptionPolicy'
type V1PreemptionPolicy string

// List of v1.PreemptionPolicy
const (
	PreemptLowerPriority V1PreemptionPolicy = "PreemptLowerPriority"
	PreemptNever V1PreemptionPolicy = "Never"
)

// All allowed values of V1PreemptionPolicy enum
var AllowedV1PreemptionPolicyEnumValues = []V1PreemptionPolicy{
	"PreemptLowerPriority",
	"Never",
}

func (v *V1PreemptionPolicy) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V1PreemptionPolicy(value)
	for _, existing := range AllowedV1PreemptionPolicyEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V1PreemptionPolicy", value)
}

// NewV1PreemptionPolicyFromValue returns a pointer to a valid V1PreemptionPolicy
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV1PreemptionPolicyFromValue(v string) (*V1PreemptionPolicy, error) {
	ev := V1PreemptionPolicy(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V1PreemptionPolicy: valid values are %v", v, AllowedV1PreemptionPolicyEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V1PreemptionPolicy) IsValid() bool {
	for _, existing := range AllowedV1PreemptionPolicyEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v1.PreemptionPolicy value
func (v V1PreemptionPolicy) Ptr() *V1PreemptionPolicy {
	return &v
}

type NullableV1PreemptionPolicy struct {
	value *V1PreemptionPolicy
	isSet bool
}

func (v NullableV1PreemptionPolicy) Get() *V1PreemptionPolicy {
	return v.value
}

func (v *NullableV1PreemptionPolicy) Set(val *V1PreemptionPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PreemptionPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PreemptionPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PreemptionPolicy(val *V1PreemptionPolicy) *NullableV1PreemptionPolicy {
	return &NullableV1PreemptionPolicy{value: val, isSet: true}
}

func (v NullableV1PreemptionPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PreemptionPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

