/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the V1alpha1StorageSpec type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1alpha1StorageSpec{}

// V1alpha1StorageSpec struct for V1alpha1StorageSpec
type V1alpha1StorageSpec struct {
	// Size is the PVC storage size (e.g. \"5Gi\"). +kubebuilder:default=\"5Gi\"
	Size *string `json:"size,omitempty"`
	// StorageClassName is the optional storage class name. +optional
	StorageClassName *string `json:"storageClassName,omitempty"`
}

// NewV1alpha1StorageSpec instantiates a new V1alpha1StorageSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1alpha1StorageSpec() *V1alpha1StorageSpec {
	this := V1alpha1StorageSpec{}
	return &this
}

// NewV1alpha1StorageSpecWithDefaults instantiates a new V1alpha1StorageSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1alpha1StorageSpecWithDefaults() *V1alpha1StorageSpec {
	this := V1alpha1StorageSpec{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *V1alpha1StorageSpec) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1StorageSpec) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *V1alpha1StorageSpec) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *V1alpha1StorageSpec) SetSize(v string) {
	o.Size = &v
}

// GetStorageClassName returns the StorageClassName field value if set, zero value otherwise.
func (o *V1alpha1StorageSpec) GetStorageClassName() string {
	if o == nil || IsNil(o.StorageClassName) {
		var ret string
		return ret
	}
	return *o.StorageClassName
}

// GetStorageClassNameOk returns a tuple with the StorageClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1alpha1StorageSpec) GetStorageClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.StorageClassName) {
		return nil, false
	}
	return o.StorageClassName, true
}

// HasStorageClassName returns a boolean if a field has been set.
func (o *V1alpha1StorageSpec) HasStorageClassName() bool {
	if o != nil && !IsNil(o.StorageClassName) {
		return true
	}

	return false
}

// SetStorageClassName gets a reference to the given string and assigns it to the StorageClassName field.
func (o *V1alpha1StorageSpec) SetStorageClassName(v string) {
	o.StorageClassName = &v
}

func (o V1alpha1StorageSpec) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1alpha1StorageSpec) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.StorageClassName) {
		toSerialize["storageClassName"] = o.StorageClassName
	}
	return toSerialize, nil
}

type NullableV1alpha1StorageSpec struct {
	value *V1alpha1StorageSpec
	isSet bool
}

func (v NullableV1alpha1StorageSpec) Get() *V1alpha1StorageSpec {
	return v.value
}

func (v *NullableV1alpha1StorageSpec) Set(val *V1alpha1StorageSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableV1alpha1StorageSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableV1alpha1StorageSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1alpha1StorageSpec(val *V1alpha1StorageSpec) *NullableV1alpha1StorageSpec {
	return &NullableV1alpha1StorageSpec{value: val, isSet: true}
}

func (v NullableV1alpha1StorageSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1alpha1StorageSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


