/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAgentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAgentRequest{}

// CreateAgentRequest struct for CreateAgentRequest
type CreateAgentRequest struct {
	// optional KomputerConnector names to attach
	Connectors []string `json:"connectors,omitempty"`
	Instructions string `json:"instructions"`
	// \"\", \"Sleep\", or \"AutoDelete\"
	Lifecycle *string `json:"lifecycle,omitempty"`
	// optional KomputerMemory names to attach
	Memories []string `json:"memories,omitempty"`
	Model *string `json:"model,omitempty"`
	Name string `json:"name"`
	// optional, defaults to server default
	Namespace *string `json:"namespace,omitempty"`
	// set by manager MCP tool
	OfficeManager *string `json:"officeManager,omitempty"`
	// \"manager\" or \"\" (default manager)
	Role *string `json:"role,omitempty"`
	// names of existing K8s Secrets to attach
	SecretRefs []string `json:"secretRefs,omitempty"`
	// optional KomputerSkill names to attach
	Skills []string `json:"skills,omitempty"`
	// optional custom system prompt
	SystemPrompt *string `json:"systemPrompt,omitempty"`
	TemplateRef *string `json:"templateRef,omitempty"`
}

type _CreateAgentRequest CreateAgentRequest

// NewCreateAgentRequest instantiates a new CreateAgentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAgentRequest(instructions string, name string) *CreateAgentRequest {
	this := CreateAgentRequest{}
	this.Instructions = instructions
	this.Name = name
	return &this
}

// NewCreateAgentRequestWithDefaults instantiates a new CreateAgentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAgentRequestWithDefaults() *CreateAgentRequest {
	this := CreateAgentRequest{}
	return &this
}

// GetConnectors returns the Connectors field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetConnectors() []string {
	if o == nil || IsNil(o.Connectors) {
		var ret []string
		return ret
	}
	return o.Connectors
}

// GetConnectorsOk returns a tuple with the Connectors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetConnectorsOk() ([]string, bool) {
	if o == nil || IsNil(o.Connectors) {
		return nil, false
	}
	return o.Connectors, true
}

// HasConnectors returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasConnectors() bool {
	if o != nil && !IsNil(o.Connectors) {
		return true
	}

	return false
}

// SetConnectors gets a reference to the given []string and assigns it to the Connectors field.
func (o *CreateAgentRequest) SetConnectors(v []string) {
	o.Connectors = v
}

// GetInstructions returns the Instructions field value
func (o *CreateAgentRequest) GetInstructions() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetInstructionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Instructions, true
}

// SetInstructions sets field value
func (o *CreateAgentRequest) SetInstructions(v string) {
	o.Instructions = v
}

// GetLifecycle returns the Lifecycle field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetLifecycle() string {
	if o == nil || IsNil(o.Lifecycle) {
		var ret string
		return ret
	}
	return *o.Lifecycle
}

// GetLifecycleOk returns a tuple with the Lifecycle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetLifecycleOk() (*string, bool) {
	if o == nil || IsNil(o.Lifecycle) {
		return nil, false
	}
	return o.Lifecycle, true
}

// HasLifecycle returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasLifecycle() bool {
	if o != nil && !IsNil(o.Lifecycle) {
		return true
	}

	return false
}

// SetLifecycle gets a reference to the given string and assigns it to the Lifecycle field.
func (o *CreateAgentRequest) SetLifecycle(v string) {
	o.Lifecycle = &v
}

// GetMemories returns the Memories field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetMemories() []string {
	if o == nil || IsNil(o.Memories) {
		var ret []string
		return ret
	}
	return o.Memories
}

// GetMemoriesOk returns a tuple with the Memories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetMemoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Memories) {
		return nil, false
	}
	return o.Memories, true
}

// HasMemories returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasMemories() bool {
	if o != nil && !IsNil(o.Memories) {
		return true
	}

	return false
}

// SetMemories gets a reference to the given []string and assigns it to the Memories field.
func (o *CreateAgentRequest) SetMemories(v []string) {
	o.Memories = v
}

// GetModel returns the Model field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetModel() string {
	if o == nil || IsNil(o.Model) {
		var ret string
		return ret
	}
	return *o.Model
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetModelOk() (*string, bool) {
	if o == nil || IsNil(o.Model) {
		return nil, false
	}
	return o.Model, true
}

// HasModel returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasModel() bool {
	if o != nil && !IsNil(o.Model) {
		return true
	}

	return false
}

// SetModel gets a reference to the given string and assigns it to the Model field.
func (o *CreateAgentRequest) SetModel(v string) {
	o.Model = &v
}

// GetName returns the Name field value
func (o *CreateAgentRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAgentRequest) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *CreateAgentRequest) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOfficeManager returns the OfficeManager field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetOfficeManager() string {
	if o == nil || IsNil(o.OfficeManager) {
		var ret string
		return ret
	}
	return *o.OfficeManager
}

// GetOfficeManagerOk returns a tuple with the OfficeManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetOfficeManagerOk() (*string, bool) {
	if o == nil || IsNil(o.OfficeManager) {
		return nil, false
	}
	return o.OfficeManager, true
}

// HasOfficeManager returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasOfficeManager() bool {
	if o != nil && !IsNil(o.OfficeManager) {
		return true
	}

	return false
}

// SetOfficeManager gets a reference to the given string and assigns it to the OfficeManager field.
func (o *CreateAgentRequest) SetOfficeManager(v string) {
	o.OfficeManager = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *CreateAgentRequest) SetRole(v string) {
	o.Role = &v
}

// GetSecretRefs returns the SecretRefs field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetSecretRefs() []string {
	if o == nil || IsNil(o.SecretRefs) {
		var ret []string
		return ret
	}
	return o.SecretRefs
}

// GetSecretRefsOk returns a tuple with the SecretRefs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetSecretRefsOk() ([]string, bool) {
	if o == nil || IsNil(o.SecretRefs) {
		return nil, false
	}
	return o.SecretRefs, true
}

// HasSecretRefs returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasSecretRefs() bool {
	if o != nil && !IsNil(o.SecretRefs) {
		return true
	}

	return false
}

// SetSecretRefs gets a reference to the given []string and assigns it to the SecretRefs field.
func (o *CreateAgentRequest) SetSecretRefs(v []string) {
	o.SecretRefs = v
}

// GetSkills returns the Skills field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetSkills() []string {
	if o == nil || IsNil(o.Skills) {
		var ret []string
		return ret
	}
	return o.Skills
}

// GetSkillsOk returns a tuple with the Skills field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetSkillsOk() ([]string, bool) {
	if o == nil || IsNil(o.Skills) {
		return nil, false
	}
	return o.Skills, true
}

// HasSkills returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasSkills() bool {
	if o != nil && !IsNil(o.Skills) {
		return true
	}

	return false
}

// SetSkills gets a reference to the given []string and assigns it to the Skills field.
func (o *CreateAgentRequest) SetSkills(v []string) {
	o.Skills = v
}

// GetSystemPrompt returns the SystemPrompt field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetSystemPrompt() string {
	if o == nil || IsNil(o.SystemPrompt) {
		var ret string
		return ret
	}
	return *o.SystemPrompt
}

// GetSystemPromptOk returns a tuple with the SystemPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetSystemPromptOk() (*string, bool) {
	if o == nil || IsNil(o.SystemPrompt) {
		return nil, false
	}
	return o.SystemPrompt, true
}

// HasSystemPrompt returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasSystemPrompt() bool {
	if o != nil && !IsNil(o.SystemPrompt) {
		return true
	}

	return false
}

// SetSystemPrompt gets a reference to the given string and assigns it to the SystemPrompt field.
func (o *CreateAgentRequest) SetSystemPrompt(v string) {
	o.SystemPrompt = &v
}

// GetTemplateRef returns the TemplateRef field value if set, zero value otherwise.
func (o *CreateAgentRequest) GetTemplateRef() string {
	if o == nil || IsNil(o.TemplateRef) {
		var ret string
		return ret
	}
	return *o.TemplateRef
}

// GetTemplateRefOk returns a tuple with the TemplateRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAgentRequest) GetTemplateRefOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateRef) {
		return nil, false
	}
	return o.TemplateRef, true
}

// HasTemplateRef returns a boolean if a field has been set.
func (o *CreateAgentRequest) HasTemplateRef() bool {
	if o != nil && !IsNil(o.TemplateRef) {
		return true
	}

	return false
}

// SetTemplateRef gets a reference to the given string and assigns it to the TemplateRef field.
func (o *CreateAgentRequest) SetTemplateRef(v string) {
	o.TemplateRef = &v
}

func (o CreateAgentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAgentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Connectors) {
		toSerialize["connectors"] = o.Connectors
	}
	toSerialize["instructions"] = o.Instructions
	if !IsNil(o.Lifecycle) {
		toSerialize["lifecycle"] = o.Lifecycle
	}
	if !IsNil(o.Memories) {
		toSerialize["memories"] = o.Memories
	}
	if !IsNil(o.Model) {
		toSerialize["model"] = o.Model
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.OfficeManager) {
		toSerialize["officeManager"] = o.OfficeManager
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.SecretRefs) {
		toSerialize["secretRefs"] = o.SecretRefs
	}
	if !IsNil(o.Skills) {
		toSerialize["skills"] = o.Skills
	}
	if !IsNil(o.SystemPrompt) {
		toSerialize["systemPrompt"] = o.SystemPrompt
	}
	if !IsNil(o.TemplateRef) {
		toSerialize["templateRef"] = o.TemplateRef
	}
	return toSerialize, nil
}

func (o *CreateAgentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"instructions",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAgentRequest := _CreateAgentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAgentRequest)

	if err != nil {
		return err
	}

	*o = CreateAgentRequest(varCreateAgentRequest)

	return err
}

type NullableCreateAgentRequest struct {
	value *CreateAgentRequest
	isSet bool
}

func (v NullableCreateAgentRequest) Get() *CreateAgentRequest {
	return v.value
}

func (v *NullableCreateAgentRequest) Set(val *CreateAgentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAgentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAgentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAgentRequest(val *CreateAgentRequest) *NullableCreateAgentRequest {
	return &NullableCreateAgentRequest{value: val, isSet: true}
}

func (v NullableCreateAgentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAgentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


