{{- if .Values.metrics.operator.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-operator-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8082
      targetPort: metrics
  selector:
    app.kubernetes.io/name: komputer
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: operator
{{- end }}
