apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents
  verbs:
  - create
  - get
  - list
  - delete
  - patch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/status
  verbs:
  - get
  - patch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeroffices
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeroffices/status
  verbs:
  - get
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputerschedules
  verbs:
  - create
  - get
  - list
  - delete
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputerschedules/status
  verbs:
  - get
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragenttemplates
  - komputeragentclustertemplates
  verbs:
  - get
  - list
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputermemories
  - komputerskills
  verbs:
  - create
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-api
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
