{{- if .Values.metrics.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.metrics.api.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: komputer
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /api/metrics
      interval: {{ .Values.metrics.api.serviceMonitor.interval }}
{{- end }}
{{- if .Values.metrics.agentMetrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-agent-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
    {{- with .Values.metrics.agentMetrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: komputer
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /agent/metrics
      interval: {{ .Values.metrics.agentMetrics.serviceMonitor.interval }}
{{- end }}
