apiVersion: komputer.komputer.ai/v1alpha1
kind: KomputerRedisConfig
metadata:
  labels:
    app.kubernetes.io/name: komputer-operator
    app.kubernetes.io/managed-by: kustomize
  name: komputerredisconfig-sample
spec:
  # TODO(user): Add fields here
