apiVersion: komputer.komputer.ai/v1alpha1
kind: KomputerConfig
metadata:
  name: default
spec:
  redis:
    address: "redis.default:6379"
    db: 0
    streamPrefix: "komputer-events"
    passwordSecret:
      name: "redis-secret"
      key: "password"
  apiURL: "http://komputer-api.default.svc.cluster.local:8080"
