/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgentListResponse,
  AgentResponse,
  CreateAgentRequest,
  PatchAgentRequest,
} from '../models/index';
import {
    AgentListResponseFromJSON,
    AgentListResponseToJSON,
    AgentResponseFromJSON,
    AgentResponseToJSON,
    CreateAgentRequestFromJSON,
    CreateAgentRequestToJSON,
    PatchAgentRequestFromJSON,
    PatchAgentRequestToJSON,
} from '../models/index';

export interface AgentsNameWsGetRequest {
    name: string;
}

export interface CancelAgentTaskRequest {
    name: string;
    namespace?: string;
}

export interface CreateAgentOperationRequest {
    request: CreateAgentRequest;
}

export interface DeleteAgentRequest {
    name: string;
    namespace?: string;
}

export interface GetAgentRequest {
    name: string;
    namespace?: string;
}

export interface GetAgentEventsRequest {
    name: string;
    namespace?: string;
    limit?: number;
}

export interface ListAgentsRequest {
    namespace?: string;
}

export interface PatchAgentOperationRequest {
    name: string;
    request: PatchAgentRequest;
    namespace?: string;
}

/**
 * 
 */
export class AgentsApi extends runtime.BaseAPI {

    /**
     * Creates request options for agentsNameWsGet without sending the request
     */
    async agentsNameWsGetRequestOpts(requestParameters: AgentsNameWsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling agentsNameWsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{name}/ws`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Upgrades to a WebSocket connection to stream real-time agent events. Events include task_started, thinking, tool_call, tool_result, text, task_completed, task_cancelled, and error.
     * Stream agent events (WebSocket)
     */
    async agentsNameWsGetRaw(requestParameters: AgentsNameWsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.agentsNameWsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Upgrades to a WebSocket connection to stream real-time agent events. Events include task_started, thinking, tool_call, tool_result, text, task_completed, task_cancelled, and error.
     * Stream agent events (WebSocket)
     */
    async agentsNameWsGet(requestParameters: AgentsNameWsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.agentsNameWsGetRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for cancelAgentTask without sending the request
     */
    async cancelAgentTaskRequestOpts(requestParameters: CancelAgentTaskRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling cancelAgentTask().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{name}/cancel`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gracefully cancels the currently running task. The agent pod stays alive for future tasks.
     * Cancel agent task
     */
    async cancelAgentTaskRaw(requestParameters: CancelAgentTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.cancelAgentTaskRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Gracefully cancels the currently running task. The agent pod stays alive for future tasks.
     * Cancel agent task
     */
    async cancelAgentTask(requestParameters: CancelAgentTaskRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.cancelAgentTaskRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createAgent without sending the request
     */
    async createAgentRequestOpts(requestParameters: CreateAgentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling createAgent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/agents`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateAgentRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Creates a new agent or sends a task to an existing idle agent (upsert by name). If the agent doesn\'t exist, it is created. If it exists and is idle, the task is forwarded.
     * Create agent or send task
     */
    async createAgentRaw(requestParameters: CreateAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        const requestOptions = await this.createAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new agent or sends a task to an existing idle agent (upsert by name). If the agent doesn\'t exist, it is created. If it exists and is idle, the task is forwarded.
     * Create agent or send task
     */
    async createAgent(requestParameters: CreateAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.createAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteAgent without sending the request
     */
    async deleteAgentRequestOpts(requestParameters: DeleteAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteAgent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the agent CR, pod, PVC, secrets, and Redis event stream.
     * Delete agent
     */
    async deleteAgentRaw(requestParameters: DeleteAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.deleteAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes the agent CR, pod, PVC, secrets, and Redis event stream.
     * Delete agent
     */
    async deleteAgent(requestParameters: DeleteAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.deleteAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgent without sending the request
     */
    async getAgentRequestOpts(requestParameters: GetAgentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getAgent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the current status and metadata for a single agent.
     * Get agent details
     */
    async getAgentRaw(requestParameters: GetAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        const requestOptions = await this.getAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Returns the current status and metadata for a single agent.
     * Get agent details
     */
    async getAgent(requestParameters: GetAgentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.getAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAgentEvents without sending the request
     */
    async getAgentEventsRequestOpts(requestParameters: GetAgentEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling getAgentEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents/{name}/events`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns recent events from the agent\'s Redis stream in chronological order.
     * Get agent events
     */
    async getAgentEventsRaw(requestParameters: GetAgentEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        const requestOptions = await this.getAgentEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns recent events from the agent\'s Redis stream in chronological order.
     * Get agent events
     */
    async getAgentEvents(requestParameters: GetAgentEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.getAgentEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAgents without sending the request
     */
    async listAgentsRequestOpts(requestParameters: ListAgentsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/agents`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all agents with their current status in the specified namespace.
     * List agents
     */
    async listAgentsRaw(requestParameters: ListAgentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentListResponse>> {
        const requestOptions = await this.listAgentsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all agents with their current status in the specified namespace.
     * List agents
     */
    async listAgents(requestParameters: ListAgentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentListResponse> {
        const response = await this.listAgentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchAgent without sending the request
     */
    async patchAgentRequestOpts(requestParameters: PatchAgentOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling patchAgent().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling patchAgent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/agents/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchAgentRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Updates model, lifecycle, instructions, secretRefs, memories, skills, or connectors on an existing agent.
     * Patch agent
     */
    async patchAgentRaw(requestParameters: PatchAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AgentResponse>> {
        const requestOptions = await this.patchAgentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AgentResponseFromJSON(jsonValue));
    }

    /**
     * Updates model, lifecycle, instructions, secretRefs, memories, skills, or connectors on an existing agent.
     * Patch agent
     */
    async patchAgent(requestParameters: PatchAgentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AgentResponse> {
        const response = await this.patchAgentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
