/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateSecretRequest,
  SecretListResponse,
  SecretResponse,
  UpdateSecretRequest,
} from '../models/index';
import {
    CreateSecretRequestFromJSON,
    CreateSecretRequestToJSON,
    SecretListResponseFromJSON,
    SecretListResponseToJSON,
    SecretResponseFromJSON,
    SecretResponseToJSON,
    UpdateSecretRequestFromJSON,
    UpdateSecretRequestToJSON,
} from '../models/index';

export interface CreateSecretOperationRequest {
    request: CreateSecretRequest;
}

export interface DeleteSecretRequest {
    name: string;
    namespace?: string;
}

export interface ListSecretsRequest {
    namespace?: string;
    all?: boolean;
}

export interface UpdateSecretOperationRequest {
    name: string;
    request: UpdateSecretRequest;
    namespace?: string;
}

/**
 * 
 */
export class SecretsApi extends runtime.BaseAPI {

    /**
     * Creates request options for createSecret without sending the request
     */
    async createSecretRequestOpts(requestParameters: CreateSecretOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling createSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/secrets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSecretRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Creates a new Kubernetes secret managed by komputer.ai that can be attached to agents.
     * Create managed secret
     */
    async createSecretRaw(requestParameters: CreateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecretResponse>> {
        const requestOptions = await this.createSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecretResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new Kubernetes secret managed by komputer.ai that can be attached to agents.
     * Create managed secret
     */
    async createSecret(requestParameters: CreateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecretResponse> {
        const response = await this.createSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteSecret without sending the request
     */
    async deleteSecretRequestOpts(requestParameters: DeleteSecretRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling deleteSecret().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/secrets/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes a managed Kubernetes secret.
     * Delete managed secret
     */
    async deleteSecretRaw(requestParameters: DeleteSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.deleteSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Deletes a managed Kubernetes secret.
     * Delete managed secret
     */
    async deleteSecret(requestParameters: DeleteSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.deleteSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listSecrets without sending the request
     */
    async listSecretsRequestOpts(requestParameters: ListSecretsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        if (requestParameters['all'] != null) {
            queryParameters['all'] = requestParameters['all'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/secrets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns all secrets with key names (not values) and attached agent counts in the specified namespace.
     * List secrets
     */
    async listSecretsRaw(requestParameters: ListSecretsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SecretListResponse>> {
        const requestOptions = await this.listSecretsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SecretListResponseFromJSON(jsonValue));
    }

    /**
     * Returns all secrets with key names (not values) and attached agent counts in the specified namespace.
     * List secrets
     */
    async listSecrets(requestParameters: ListSecretsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SecretListResponse> {
        const response = await this.listSecretsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateSecret without sending the request
     */
    async updateSecretRequestOpts(requestParameters: UpdateSecretOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling updateSecret().'
            );
        }

        if (requestParameters['request'] == null) {
            throw new runtime.RequiredError(
                'request',
                'Required parameter "request" was null or undefined when calling updateSecret().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['namespace'] != null) {
            queryParameters['namespace'] = requestParameters['namespace'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/secrets/{name}`;
        urlPath = urlPath.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSecretRequestToJSON(requestParameters['request']),
        };
    }

    /**
     * Replaces the key-value pairs in a managed Kubernetes secret.
     * Update managed secret
     */
    async updateSecretRaw(requestParameters: UpdateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        const requestOptions = await this.updateSecretRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Replaces the key-value pairs in a managed Kubernetes secret.
     * Update managed secret
     */
    async updateSecret(requestParameters: UpdateSecretOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.updateSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
