apiVersion: komputer.komputer.ai/v1alpha1
kind: KomputerConfig
metadata:
  name: default
  labels:
    {{- include "komputer.labels" . | nindent 4 }}
spec:
  redis:
    address: {{ include "komputer.redisAddress" . }}
    db: {{ .Values.config.redis.db }}
    streamPrefix: {{ .Values.config.redis.streamPrefix }}
    {{- if and (not .Values.redis.enabled) .Values.externalRedis.passwordSecret.name }}
    passwordSecret:
      name: {{ .Values.externalRedis.passwordSecret.name }}
      key: {{ .Values.externalRedis.passwordSecret.key }}
      {{- if .Values.externalRedis.passwordSecret.namespace }}
      namespace: {{ .Values.externalRedis.passwordSecret.namespace }}
      {{- end }}
    {{- end }}
  apiURL: {{ include "komputer.apiURL" . }}
