# coding: utf-8

"""
    komputer.ai API

    API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IntstrType(int, Enum):
    """
    IntstrType
    """

    """
    allowed enum values
    """
    Int = 0
    String = 1

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IntstrType from a JSON string"""
        return cls(json.loads(json_str))


