/*
komputer.ai API

API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package komputer

import (
	"encoding/json"
)

// checks if the OfficeListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OfficeListResponse{}

// OfficeListResponse struct for OfficeListResponse
type OfficeListResponse struct {
	Offices []OfficeResponse `json:"offices,omitempty"`
}

// NewOfficeListResponse instantiates a new OfficeListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOfficeListResponse() *OfficeListResponse {
	this := OfficeListResponse{}
	return &this
}

// NewOfficeListResponseWithDefaults instantiates a new OfficeListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOfficeListResponseWithDefaults() *OfficeListResponse {
	this := OfficeListResponse{}
	return &this
}

// GetOffices returns the Offices field value if set, zero value otherwise.
func (o *OfficeListResponse) GetOffices() []OfficeResponse {
	if o == nil || IsNil(o.Offices) {
		var ret []OfficeResponse
		return ret
	}
	return o.Offices
}

// GetOfficesOk returns a tuple with the Offices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OfficeListResponse) GetOfficesOk() ([]OfficeResponse, bool) {
	if o == nil || IsNil(o.Offices) {
		return nil, false
	}
	return o.Offices, true
}

// HasOffices returns a boolean if a field has been set.
func (o *OfficeListResponse) HasOffices() bool {
	if o != nil && !IsNil(o.Offices) {
		return true
	}

	return false
}

// SetOffices gets a reference to the given []OfficeResponse and assigns it to the Offices field.
func (o *OfficeListResponse) SetOffices(v []OfficeResponse) {
	o.Offices = v
}

func (o OfficeListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OfficeListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Offices) {
		toSerialize["offices"] = o.Offices
	}
	return toSerialize, nil
}

type NullableOfficeListResponse struct {
	value *OfficeListResponse
	isSet bool
}

func (v NullableOfficeListResponse) Get() *OfficeListResponse {
	return v.value
}

func (v *NullableOfficeListResponse) Set(val *OfficeListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOfficeListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOfficeListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOfficeListResponse(val *OfficeListResponse) *NullableOfficeListResponse {
	return &NullableOfficeListResponse{value: val, isSet: true}
}

func (v NullableOfficeListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOfficeListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


