/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMemoryRequest
 */
export interface CreateMemoryRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateMemoryRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemoryRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemoryRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMemoryRequest
     */
    namespace?: string;
}

/**
 * Check if a given object implements the CreateMemoryRequest interface.
 */
export function instanceOfCreateMemoryRequest(value: object): value is CreateMemoryRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateMemoryRequestFromJSON(json: any): CreateMemoryRequest {
    return CreateMemoryRequestFromJSONTyped(json, false);
}

export function CreateMemoryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMemoryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
    };
}

export function CreateMemoryRequestToJSON(json: any): CreateMemoryRequest {
    return CreateMemoryRequestToJSONTyped(json, false);
}

export function CreateMemoryRequestToJSONTyped(value?: CreateMemoryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'description': value['description'],
        'name': value['name'],
        'namespace': value['namespace'],
    };
}

