/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSkillRequest
 */
export interface CreateSkillRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSkillRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSkillRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSkillRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSkillRequest
     */
    namespace?: string;
}

/**
 * Check if a given object implements the CreateSkillRequest interface.
 */
export function instanceOfCreateSkillRequest(value: object): value is CreateSkillRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateSkillRequestFromJSON(json: any): CreateSkillRequest {
    return CreateSkillRequestFromJSONTyped(json, false);
}

export function CreateSkillRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSkillRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'description': json['description'],
        'name': json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
    };
}

export function CreateSkillRequestToJSON(json: any): CreateSkillRequest {
    return CreateSkillRequestToJSONTyped(json, false);
}

export function CreateSkillRequestToJSONTyped(value?: CreateSkillRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'description': value['description'],
        'name': value['name'],
        'namespace': value['namespace'],
    };
}

