/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchAgentRequest
 */
export interface PatchAgentRequest {
    /**
     * connector names to attach
     * @type {Array<string>}
     * @memberof PatchAgentRequest
     */
    connectors?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchAgentRequest
     */
    instructions?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchAgentRequest
     */
    lifecycle?: string;
    /**
     * memory names to attach
     * @type {Array<string>}
     * @memberof PatchAgentRequest
     */
    memories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PatchAgentRequest
     */
    model?: string;
    /**
     * full replacement list of K8s secret names
     * @type {Array<string>}
     * @memberof PatchAgentRequest
     */
    secretRefs?: Array<string>;
    /**
     * skill names to attach
     * @type {Array<string>}
     * @memberof PatchAgentRequest
     */
    skills?: Array<string>;
    /**
     * custom system prompt
     * @type {string}
     * @memberof PatchAgentRequest
     */
    systemPrompt?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchAgentRequest
     */
    templateRef?: string;
}

/**
 * Check if a given object implements the PatchAgentRequest interface.
 */
export function instanceOfPatchAgentRequest(value: object): value is PatchAgentRequest {
    return true;
}

export function PatchAgentRequestFromJSON(json: any): PatchAgentRequest {
    return PatchAgentRequestFromJSONTyped(json, false);
}

export function PatchAgentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAgentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'connectors': json['connectors'] == null ? undefined : json['connectors'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
        'lifecycle': json['lifecycle'] == null ? undefined : json['lifecycle'],
        'memories': json['memories'] == null ? undefined : json['memories'],
        'model': json['model'] == null ? undefined : json['model'],
        'secretRefs': json['secretRefs'] == null ? undefined : json['secretRefs'],
        'skills': json['skills'] == null ? undefined : json['skills'],
        'systemPrompt': json['systemPrompt'] == null ? undefined : json['systemPrompt'],
        'templateRef': json['templateRef'] == null ? undefined : json['templateRef'],
    };
}

export function PatchAgentRequestToJSON(json: any): PatchAgentRequest {
    return PatchAgentRequestToJSONTyped(json, false);
}

export function PatchAgentRequestToJSONTyped(value?: PatchAgentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'connectors': value['connectors'],
        'instructions': value['instructions'],
        'lifecycle': value['lifecycle'],
        'memories': value['memories'],
        'model': value['model'],
        'secretRefs': value['secretRefs'],
        'skills': value['skills'],
        'systemPrompt': value['systemPrompt'],
        'templateRef': value['templateRef'],
    };
}

