/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SecretResponse } from './SecretResponse';
import {
    SecretResponseFromJSON,
    SecretResponseFromJSONTyped,
    SecretResponseToJSON,
    SecretResponseToJSONTyped,
} from './SecretResponse';

/**
 * 
 * @export
 * @interface SecretListResponse
 */
export interface SecretListResponse {
    /**
     * 
     * @type {Array<SecretResponse>}
     * @memberof SecretListResponse
     */
    secrets?: Array<SecretResponse>;
}

/**
 * Check if a given object implements the SecretListResponse interface.
 */
export function instanceOfSecretListResponse(value: object): value is SecretListResponse {
    return true;
}

export function SecretListResponseFromJSON(json: any): SecretListResponse {
    return SecretListResponseFromJSONTyped(json, false);
}

export function SecretListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'secrets': json['secrets'] == null ? undefined : ((json['secrets'] as Array<any>).map(SecretResponseFromJSON)),
    };
}

export function SecretListResponseToJSON(json: any): SecretListResponse {
    return SecretListResponseToJSONTyped(json, false);
}

export function SecretListResponseToJSONTyped(value?: SecretListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secrets': value['secrets'] == null ? undefined : ((value['secrets'] as Array<any>).map(SecretResponseToJSON)),
    };
}

