/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1AzureDataDiskCachingMode } from './V1AzureDataDiskCachingMode';
import {
    V1AzureDataDiskCachingModeFromJSON,
    V1AzureDataDiskCachingModeFromJSONTyped,
    V1AzureDataDiskCachingModeToJSON,
    V1AzureDataDiskCachingModeToJSONTyped,
} from './V1AzureDataDiskCachingMode';
import type { V1AzureDataDiskKind } from './V1AzureDataDiskKind';
import {
    V1AzureDataDiskKindFromJSON,
    V1AzureDataDiskKindFromJSONTyped,
    V1AzureDataDiskKindToJSON,
    V1AzureDataDiskKindToJSONTyped,
} from './V1AzureDataDiskKind';

/**
 * 
 * @export
 * @interface V1AzureDiskVolumeSource
 */
export interface V1AzureDiskVolumeSource {
    /**
     * cachingMode is the Host Caching mode: None, Read Only, Read Write.
     * +optional
     * +default=ref(AzureDataDiskCachingReadWrite)
     * @type {V1AzureDataDiskCachingMode}
     * @memberof V1AzureDiskVolumeSource
     */
    cachingMode?: V1AzureDataDiskCachingMode;
    /**
     * diskName is the Name of the data disk in the blob storage
     * @type {string}
     * @memberof V1AzureDiskVolumeSource
     */
    diskName?: string;
    /**
     * diskURI is the URI of data disk in the blob storage
     * @type {string}
     * @memberof V1AzureDiskVolumeSource
     */
    diskURI?: string;
    /**
     * fsType is Filesystem type to mount.
     * Must be a filesystem type supported by the host operating system.
     * Ex. "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     * +optional
     * +default="ext4"
     * @type {string}
     * @memberof V1AzureDiskVolumeSource
     */
    fsType?: string;
    /**
     * kind expected values are Shared: multiple blob disks per storage account  Dedicated: single blob disk per storage account  Managed: azure managed data disk (only in managed availability set). defaults to shared
     * +default=ref(AzureSharedBlobDisk)
     * @type {V1AzureDataDiskKind}
     * @memberof V1AzureDiskVolumeSource
     */
    kind?: V1AzureDataDiskKind;
    /**
     * readOnly Defaults to false (read/write). ReadOnly here will force
     * the ReadOnly setting in VolumeMounts.
     * +optional
     * +default=false
     * @type {boolean}
     * @memberof V1AzureDiskVolumeSource
     */
    readOnly?: boolean;
}



/**
 * Check if a given object implements the V1AzureDiskVolumeSource interface.
 */
export function instanceOfV1AzureDiskVolumeSource(value: object): value is V1AzureDiskVolumeSource {
    return true;
}

export function V1AzureDiskVolumeSourceFromJSON(json: any): V1AzureDiskVolumeSource {
    return V1AzureDiskVolumeSourceFromJSONTyped(json, false);
}

export function V1AzureDiskVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AzureDiskVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'cachingMode': json['cachingMode'] == null ? undefined : V1AzureDataDiskCachingModeFromJSON(json['cachingMode']),
        'diskName': json['diskName'] == null ? undefined : json['diskName'],
        'diskURI': json['diskURI'] == null ? undefined : json['diskURI'],
        'fsType': json['fsType'] == null ? undefined : json['fsType'],
        'kind': json['kind'] == null ? undefined : V1AzureDataDiskKindFromJSON(json['kind']),
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
    };
}

export function V1AzureDiskVolumeSourceToJSON(json: any): V1AzureDiskVolumeSource {
    return V1AzureDiskVolumeSourceToJSONTyped(json, false);
}

export function V1AzureDiskVolumeSourceToJSONTyped(value?: V1AzureDiskVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cachingMode': V1AzureDataDiskCachingModeToJSON(value['cachingMode']),
        'diskName': value['diskName'],
        'diskURI': value['diskURI'],
        'fsType': value['fsType'],
        'kind': V1AzureDataDiskKindToJSON(value['kind']),
        'readOnly': value['readOnly'],
    };
}

