/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1AzureFileVolumeSource
 */
export interface V1AzureFileVolumeSource {
    /**
     * readOnly defaults to false (read/write). ReadOnly here will force
     * the ReadOnly setting in VolumeMounts.
     * +optional
     * @type {boolean}
     * @memberof V1AzureFileVolumeSource
     */
    readOnly?: boolean;
    /**
     * secretName is the  name of secret that contains Azure Storage Account Name and Key
     * @type {string}
     * @memberof V1AzureFileVolumeSource
     */
    secretName?: string;
    /**
     * shareName is the azure share Name
     * @type {string}
     * @memberof V1AzureFileVolumeSource
     */
    shareName?: string;
}

/**
 * Check if a given object implements the V1AzureFileVolumeSource interface.
 */
export function instanceOfV1AzureFileVolumeSource(value: object): value is V1AzureFileVolumeSource {
    return true;
}

export function V1AzureFileVolumeSourceFromJSON(json: any): V1AzureFileVolumeSource {
    return V1AzureFileVolumeSourceFromJSONTyped(json, false);
}

export function V1AzureFileVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1AzureFileVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
        'secretName': json['secretName'] == null ? undefined : json['secretName'],
        'shareName': json['shareName'] == null ? undefined : json['shareName'],
    };
}

export function V1AzureFileVolumeSourceToJSON(json: any): V1AzureFileVolumeSource {
    return V1AzureFileVolumeSourceToJSONTyped(json, false);
}

export function V1AzureFileVolumeSourceToJSONTyped(value?: V1AzureFileVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'readOnly': value['readOnly'],
        'secretName': value['secretName'],
        'shareName': value['shareName'],
    };
}

