/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1LocalObjectReference } from './V1LocalObjectReference';
import {
    V1LocalObjectReferenceFromJSON,
    V1LocalObjectReferenceFromJSONTyped,
    V1LocalObjectReferenceToJSON,
    V1LocalObjectReferenceToJSONTyped,
} from './V1LocalObjectReference';

/**
 * 
 * @export
 * @interface V1CinderVolumeSource
 */
export interface V1CinderVolumeSource {
    /**
     * fsType is the filesystem type to mount.
     * Must be a filesystem type supported by the host operating system.
     * Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     * More info: https://examples.k8s.io/mysql-cinder-pd/README.md
     * +optional
     * @type {string}
     * @memberof V1CinderVolumeSource
     */
    fsType?: string;
    /**
     * readOnly defaults to false (read/write). ReadOnly here will force
     * the ReadOnly setting in VolumeMounts.
     * More info: https://examples.k8s.io/mysql-cinder-pd/README.md
     * +optional
     * @type {boolean}
     * @memberof V1CinderVolumeSource
     */
    readOnly?: boolean;
    /**
     * secretRef is optional: points to a secret object containing parameters used to connect
     * to OpenStack.
     * +optional
     * @type {V1LocalObjectReference}
     * @memberof V1CinderVolumeSource
     */
    secretRef?: V1LocalObjectReference;
    /**
     * volumeID used to identify the volume in cinder.
     * More info: https://examples.k8s.io/mysql-cinder-pd/README.md
     * @type {string}
     * @memberof V1CinderVolumeSource
     */
    volumeID?: string;
}

/**
 * Check if a given object implements the V1CinderVolumeSource interface.
 */
export function instanceOfV1CinderVolumeSource(value: object): value is V1CinderVolumeSource {
    return true;
}

export function V1CinderVolumeSourceFromJSON(json: any): V1CinderVolumeSource {
    return V1CinderVolumeSourceFromJSONTyped(json, false);
}

export function V1CinderVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CinderVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'fsType': json['fsType'] == null ? undefined : json['fsType'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
        'secretRef': json['secretRef'] == null ? undefined : V1LocalObjectReferenceFromJSON(json['secretRef']),
        'volumeID': json['volumeID'] == null ? undefined : json['volumeID'],
    };
}

export function V1CinderVolumeSourceToJSON(json: any): V1CinderVolumeSource {
    return V1CinderVolumeSourceToJSONTyped(json, false);
}

export function V1CinderVolumeSourceToJSONTyped(value?: V1CinderVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fsType': value['fsType'],
        'readOnly': value['readOnly'],
        'secretRef': V1LocalObjectReferenceToJSON(value['secretRef']),
        'volumeID': value['volumeID'],
    };
}

