/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1ContainerRestartRuleAction = {
    ContainerRestartRuleActionRestart: 'Restart',
    ContainerRestartRuleActionRestartAllContainers: 'RestartAllContainers'
} as const;
export type V1ContainerRestartRuleAction = typeof V1ContainerRestartRuleAction[keyof typeof V1ContainerRestartRuleAction];


export function instanceOfV1ContainerRestartRuleAction(value: any): boolean {
    for (const key in V1ContainerRestartRuleAction) {
        if (Object.prototype.hasOwnProperty.call(V1ContainerRestartRuleAction, key)) {
            if (V1ContainerRestartRuleAction[key as keyof typeof V1ContainerRestartRuleAction] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1ContainerRestartRuleActionFromJSON(json: any): V1ContainerRestartRuleAction {
    return V1ContainerRestartRuleActionFromJSONTyped(json, false);
}

export function V1ContainerRestartRuleActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ContainerRestartRuleAction {
    return json as V1ContainerRestartRuleAction;
}

export function V1ContainerRestartRuleActionToJSON(value?: V1ContainerRestartRuleAction | null): any {
    return value as any;
}

export function V1ContainerRestartRuleActionToJSONTyped(value: any, ignoreDiscriminator: boolean): V1ContainerRestartRuleAction {
    return value as V1ContainerRestartRuleAction;
}

