/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ResourceName } from './V1ResourceName';
import {
    V1ResourceNameFromJSON,
    V1ResourceNameFromJSONTyped,
    V1ResourceNameToJSON,
    V1ResourceNameToJSONTyped,
} from './V1ResourceName';
import type { V1ResourceResizeRestartPolicy } from './V1ResourceResizeRestartPolicy';
import {
    V1ResourceResizeRestartPolicyFromJSON,
    V1ResourceResizeRestartPolicyFromJSONTyped,
    V1ResourceResizeRestartPolicyToJSON,
    V1ResourceResizeRestartPolicyToJSONTyped,
} from './V1ResourceResizeRestartPolicy';

/**
 * 
 * @export
 * @interface V1ContainerResizePolicy
 */
export interface V1ContainerResizePolicy {
    /**
     * Name of the resource to which this resource resize policy applies.
     * Supported values: cpu, memory.
     * @type {V1ResourceName}
     * @memberof V1ContainerResizePolicy
     */
    resourceName?: V1ResourceName;
    /**
     * Restart policy to apply when specified resource is resized.
     * If not specified, it defaults to NotRequired.
     * @type {V1ResourceResizeRestartPolicy}
     * @memberof V1ContainerResizePolicy
     */
    restartPolicy?: V1ResourceResizeRestartPolicy;
}



/**
 * Check if a given object implements the V1ContainerResizePolicy interface.
 */
export function instanceOfV1ContainerResizePolicy(value: object): value is V1ContainerResizePolicy {
    return true;
}

export function V1ContainerResizePolicyFromJSON(json: any): V1ContainerResizePolicy {
    return V1ContainerResizePolicyFromJSONTyped(json, false);
}

export function V1ContainerResizePolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ContainerResizePolicy {
    if (json == null) {
        return json;
    }
    return {
        
        'resourceName': json['resourceName'] == null ? undefined : V1ResourceNameFromJSON(json['resourceName']),
        'restartPolicy': json['restartPolicy'] == null ? undefined : V1ResourceResizeRestartPolicyFromJSON(json['restartPolicy']),
    };
}

export function V1ContainerResizePolicyToJSON(json: any): V1ContainerResizePolicy {
    return V1ContainerResizePolicyToJSONTyped(json, false);
}

export function V1ContainerResizePolicyToJSONTyped(value?: V1ContainerResizePolicy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resourceName': V1ResourceNameToJSON(value['resourceName']),
        'restartPolicy': V1ResourceResizeRestartPolicyToJSON(value['restartPolicy']),
    };
}

