/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1Lifecycle } from './V1Lifecycle';
import {
    V1LifecycleFromJSON,
    V1LifecycleFromJSONTyped,
    V1LifecycleToJSON,
    V1LifecycleToJSONTyped,
} from './V1Lifecycle';
import type { V1ContainerRestartRule } from './V1ContainerRestartRule';
import {
    V1ContainerRestartRuleFromJSON,
    V1ContainerRestartRuleFromJSONTyped,
    V1ContainerRestartRuleToJSON,
    V1ContainerRestartRuleToJSONTyped,
} from './V1ContainerRestartRule';
import type { V1ContainerPort } from './V1ContainerPort';
import {
    V1ContainerPortFromJSON,
    V1ContainerPortFromJSONTyped,
    V1ContainerPortToJSON,
    V1ContainerPortToJSONTyped,
} from './V1ContainerPort';
import type { V1Probe } from './V1Probe';
import {
    V1ProbeFromJSON,
    V1ProbeFromJSONTyped,
    V1ProbeToJSON,
    V1ProbeToJSONTyped,
} from './V1Probe';
import type { V1SecurityContext } from './V1SecurityContext';
import {
    V1SecurityContextFromJSON,
    V1SecurityContextFromJSONTyped,
    V1SecurityContextToJSON,
    V1SecurityContextToJSONTyped,
} from './V1SecurityContext';
import type { V1EnvVar } from './V1EnvVar';
import {
    V1EnvVarFromJSON,
    V1EnvVarFromJSONTyped,
    V1EnvVarToJSON,
    V1EnvVarToJSONTyped,
} from './V1EnvVar';
import type { V1ContainerResizePolicy } from './V1ContainerResizePolicy';
import {
    V1ContainerResizePolicyFromJSON,
    V1ContainerResizePolicyFromJSONTyped,
    V1ContainerResizePolicyToJSON,
    V1ContainerResizePolicyToJSONTyped,
} from './V1ContainerResizePolicy';
import type { V1ContainerRestartPolicy } from './V1ContainerRestartPolicy';
import {
    V1ContainerRestartPolicyFromJSON,
    V1ContainerRestartPolicyFromJSONTyped,
    V1ContainerRestartPolicyToJSON,
    V1ContainerRestartPolicyToJSONTyped,
} from './V1ContainerRestartPolicy';
import type { V1VolumeMount } from './V1VolumeMount';
import {
    V1VolumeMountFromJSON,
    V1VolumeMountFromJSONTyped,
    V1VolumeMountToJSON,
    V1VolumeMountToJSONTyped,
} from './V1VolumeMount';
import type { V1EnvFromSource } from './V1EnvFromSource';
import {
    V1EnvFromSourceFromJSON,
    V1EnvFromSourceFromJSONTyped,
    V1EnvFromSourceToJSON,
    V1EnvFromSourceToJSONTyped,
} from './V1EnvFromSource';
import type { V1PullPolicy } from './V1PullPolicy';
import {
    V1PullPolicyFromJSON,
    V1PullPolicyFromJSONTyped,
    V1PullPolicyToJSON,
    V1PullPolicyToJSONTyped,
} from './V1PullPolicy';
import type { V1TerminationMessagePolicy } from './V1TerminationMessagePolicy';
import {
    V1TerminationMessagePolicyFromJSON,
    V1TerminationMessagePolicyFromJSONTyped,
    V1TerminationMessagePolicyToJSON,
    V1TerminationMessagePolicyToJSONTyped,
} from './V1TerminationMessagePolicy';
import type { V1ResourceRequirements } from './V1ResourceRequirements';
import {
    V1ResourceRequirementsFromJSON,
    V1ResourceRequirementsFromJSONTyped,
    V1ResourceRequirementsToJSON,
    V1ResourceRequirementsToJSONTyped,
} from './V1ResourceRequirements';
import type { V1VolumeDevice } from './V1VolumeDevice';
import {
    V1VolumeDeviceFromJSON,
    V1VolumeDeviceFromJSONTyped,
    V1VolumeDeviceToJSON,
    V1VolumeDeviceToJSONTyped,
} from './V1VolumeDevice';

/**
 * 
 * @export
 * @interface V1Container
 */
export interface V1Container {
    /**
     * Arguments to the entrypoint.
     * The container image's CMD is used if this is not provided.
     * Variable references $(VAR_NAME) are expanded using the container's environment. If a variable
     * cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced
     * to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will
     * produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless
     * of whether the variable exists or not. Cannot be updated.
     * More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
     * +optional
     * +listType=atomic
     * @type {Array<string>}
     * @memberof V1Container
     */
    args?: Array<string>;
    /**
     * Entrypoint array. Not executed within a shell.
     * The container image's ENTRYPOINT is used if this is not provided.
     * Variable references $(VAR_NAME) are expanded using the container's environment. If a variable
     * cannot be resolved, the reference in the input string will be unchanged. Double $$ are reduced
     * to a single $, which allows for escaping the $(VAR_NAME) syntax: i.e. "$$(VAR_NAME)" will
     * produce the string literal "$(VAR_NAME)". Escaped references will never be expanded, regardless
     * of whether the variable exists or not. Cannot be updated.
     * More info: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#running-a-command-in-a-shell
     * +optional
     * +listType=atomic
     * @type {Array<string>}
     * @memberof V1Container
     */
    command?: Array<string>;
    /**
     * List of environment variables to set in the container.
     * Cannot be updated.
     * +optional
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1EnvVar>}
     * @memberof V1Container
     */
    env?: Array<V1EnvVar>;
    /**
     * List of sources to populate environment variables in the container.
     * The keys defined within a source may consist of any printable ASCII characters except '='.
     * When a key exists in multiple
     * sources, the value associated with the last source will take precedence.
     * Values defined by an Env with a duplicate key will take precedence.
     * Cannot be updated.
     * +optional
     * +listType=atomic
     * @type {Array<V1EnvFromSource>}
     * @memberof V1Container
     */
    envFrom?: Array<V1EnvFromSource>;
    /**
     * Container image name.
     * More info: https://kubernetes.io/docs/concepts/containers/images
     * This field is optional to allow higher level config management to default or override
     * container images in workload controllers like Deployments and StatefulSets.
     * +optional
     * @type {string}
     * @memberof V1Container
     */
    image?: string;
    /**
     * Image pull policy.
     * One of Always, Never, IfNotPresent.
     * Defaults to Always if :latest tag is specified, or IfNotPresent otherwise.
     * Cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/containers/images#updating-images
     * +optional
     * @type {V1PullPolicy}
     * @memberof V1Container
     */
    imagePullPolicy?: V1PullPolicy;
    /**
     * Actions that the management system should take in response to container lifecycle events.
     * Cannot be updated.
     * +optional
     * @type {V1Lifecycle}
     * @memberof V1Container
     */
    lifecycle?: V1Lifecycle;
    /**
     * Periodic probe of container liveness.
     * Container will be restarted if the probe fails.
     * Cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
     * +optional
     * @type {V1Probe}
     * @memberof V1Container
     */
    livenessProbe?: V1Probe;
    /**
     * Name of the container specified as a DNS_LABEL.
     * Each container in a pod must have a unique name (DNS_LABEL).
     * Cannot be updated.
     * @type {string}
     * @memberof V1Container
     */
    name?: string;
    /**
     * List of ports to expose from the container. Not specifying a port here
     * DOES NOT prevent that port from being exposed. Any port which is
     * listening on the default "0.0.0.0" address inside a container will be
     * accessible from the network.
     * Modifying this array with strategic merge patch may corrupt the data.
     * For more information See https://github.com/kubernetes/kubernetes/issues/108255.
     * Cannot be updated.
     * +optional
     * +patchMergeKey=containerPort
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=containerPort
     * +listMapKey=protocol
     * @type {Array<V1ContainerPort>}
     * @memberof V1Container
     */
    ports?: Array<V1ContainerPort>;
    /**
     * Periodic probe of container service readiness.
     * Container will be removed from service endpoints if the probe fails.
     * Cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
     * +optional
     * @type {V1Probe}
     * @memberof V1Container
     */
    readinessProbe?: V1Probe;
    /**
     * Resources resize policy for the container.
     * This field cannot be set on ephemeral containers.
     * +featureGate=InPlacePodVerticalScaling
     * +optional
     * +listType=atomic
     * @type {Array<V1ContainerResizePolicy>}
     * @memberof V1Container
     */
    resizePolicy?: Array<V1ContainerResizePolicy>;
    /**
     * Compute Resources required by this container.
     * Cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
     * +optional
     * @type {V1ResourceRequirements}
     * @memberof V1Container
     */
    resources?: V1ResourceRequirements;
    /**
     * RestartPolicy defines the restart behavior of individual containers in a pod.
     * This overrides the pod-level restart policy. When this field is not specified,
     * the restart behavior is defined by the Pod's restart policy and the container type.
     * Additionally, setting the RestartPolicy as "Always" for the init container will
     * have the following effect:
     * this init container will be continually restarted on
     * exit until all regular containers have terminated. Once all regular
     * containers have completed, all init containers with restartPolicy "Always"
     * will be shut down. This lifecycle differs from normal init containers and
     * is often referred to as a "sidecar" container. Although this init
     * container still starts in the init container sequence, it does not wait
     * for the container to complete before proceeding to the next init
     * container. Instead, the next init container starts immediately after this
     * init container is started, or after any startupProbe has successfully
     * completed.
     * +optional
     * @type {V1ContainerRestartPolicy}
     * @memberof V1Container
     */
    restartPolicy?: V1ContainerRestartPolicy;
    /**
     * Represents a list of rules to be checked to determine if the
     * container should be restarted on exit. The rules are evaluated in
     * order. Once a rule matches a container exit condition, the remaining
     * rules are ignored. If no rule matches the container exit condition,
     * the Container-level restart policy determines the whether the container
     * is restarted or not. Constraints on the rules:
     * - At most 20 rules are allowed.
     * - Rules can have the same action.
     * - Identical rules are not forbidden in validations.
     * When rules are specified, container MUST set RestartPolicy explicitly
     * even it if matches the Pod's RestartPolicy.
     * +featureGate=ContainerRestartRules
     * +optional
     * +listType=atomic
     * @type {Array<V1ContainerRestartRule>}
     * @memberof V1Container
     */
    restartPolicyRules?: Array<V1ContainerRestartRule>;
    /**
     * SecurityContext defines the security options the container should be run with.
     * If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext.
     * More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
     * +optional
     * @type {V1SecurityContext}
     * @memberof V1Container
     */
    securityContext?: V1SecurityContext;
    /**
     * StartupProbe indicates that the Pod has successfully initialized.
     * If specified, no other probes are executed until this completes successfully.
     * If this probe fails, the Pod will be restarted, just as if the livenessProbe failed.
     * This can be used to provide different probe parameters at the beginning of a Pod's lifecycle,
     * when it might take a long time to load data or warm a cache, than during steady-state operation.
     * This cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
     * +optional
     * @type {V1Probe}
     * @memberof V1Container
     */
    startupProbe?: V1Probe;
    /**
     * Whether this container should allocate a buffer for stdin in the container runtime. If this
     * is not set, reads from stdin in the container will always result in EOF.
     * Default is false.
     * +optional
     * @type {boolean}
     * @memberof V1Container
     */
    stdin?: boolean;
    /**
     * Whether the container runtime should close the stdin channel after it has been opened by
     * a single attach. When stdin is true the stdin stream will remain open across multiple attach
     * sessions. If stdinOnce is set to true, stdin is opened on container start, is empty until the
     * first client attaches to stdin, and then remains open and accepts data until the client disconnects,
     * at which time stdin is closed and remains closed until the container is restarted. If this
     * flag is false, a container processes that reads from stdin will never receive an EOF.
     * Default is false
     * +optional
     * @type {boolean}
     * @memberof V1Container
     */
    stdinOnce?: boolean;
    /**
     * Optional: Path at which the file to which the container's termination message
     * will be written is mounted into the container's filesystem.
     * Message written is intended to be brief final status, such as an assertion failure message.
     * Will be truncated by the node if greater than 4096 bytes. The total message length across
     * all containers will be limited to 12kb.
     * Defaults to /dev/termination-log.
     * Cannot be updated.
     * +optional
     * @type {string}
     * @memberof V1Container
     */
    terminationMessagePath?: string;
    /**
     * Indicate how the termination message should be populated. File will use the contents of
     * terminationMessagePath to populate the container status message on both success and failure.
     * FallbackToLogsOnError will use the last chunk of container log output if the termination
     * message file is empty and the container exited with an error.
     * The log output is limited to 2048 bytes or 80 lines, whichever is smaller.
     * Defaults to File.
     * Cannot be updated.
     * +optional
     * @type {V1TerminationMessagePolicy}
     * @memberof V1Container
     */
    terminationMessagePolicy?: V1TerminationMessagePolicy;
    /**
     * Whether this container should allocate a TTY for itself, also requires 'stdin' to be true.
     * Default is false.
     * +optional
     * @type {boolean}
     * @memberof V1Container
     */
    tty?: boolean;
    /**
     * volumeDevices is the list of block devices to be used by the container.
     * +patchMergeKey=devicePath
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=devicePath
     * +optional
     * @type {Array<V1VolumeDevice>}
     * @memberof V1Container
     */
    volumeDevices?: Array<V1VolumeDevice>;
    /**
     * Pod volumes to mount into the container's filesystem.
     * Cannot be updated.
     * +optional
     * +patchMergeKey=mountPath
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=mountPath
     * @type {Array<V1VolumeMount>}
     * @memberof V1Container
     */
    volumeMounts?: Array<V1VolumeMount>;
    /**
     * Container's working directory.
     * If not specified, the container runtime's default will be used, which
     * might be configured in the container image.
     * Cannot be updated.
     * +optional
     * @type {string}
     * @memberof V1Container
     */
    workingDir?: string;
}



/**
 * Check if a given object implements the V1Container interface.
 */
export function instanceOfV1Container(value: object): value is V1Container {
    return true;
}

export function V1ContainerFromJSON(json: any): V1Container {
    return V1ContainerFromJSONTyped(json, false);
}

export function V1ContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Container {
    if (json == null) {
        return json;
    }
    return {
        
        'args': json['args'] == null ? undefined : json['args'],
        'command': json['command'] == null ? undefined : json['command'],
        'env': json['env'] == null ? undefined : ((json['env'] as Array<any>).map(V1EnvVarFromJSON)),
        'envFrom': json['envFrom'] == null ? undefined : ((json['envFrom'] as Array<any>).map(V1EnvFromSourceFromJSON)),
        'image': json['image'] == null ? undefined : json['image'],
        'imagePullPolicy': json['imagePullPolicy'] == null ? undefined : V1PullPolicyFromJSON(json['imagePullPolicy']),
        'lifecycle': json['lifecycle'] == null ? undefined : V1LifecycleFromJSON(json['lifecycle']),
        'livenessProbe': json['livenessProbe'] == null ? undefined : V1ProbeFromJSON(json['livenessProbe']),
        'name': json['name'] == null ? undefined : json['name'],
        'ports': json['ports'] == null ? undefined : ((json['ports'] as Array<any>).map(V1ContainerPortFromJSON)),
        'readinessProbe': json['readinessProbe'] == null ? undefined : V1ProbeFromJSON(json['readinessProbe']),
        'resizePolicy': json['resizePolicy'] == null ? undefined : ((json['resizePolicy'] as Array<any>).map(V1ContainerResizePolicyFromJSON)),
        'resources': json['resources'] == null ? undefined : V1ResourceRequirementsFromJSON(json['resources']),
        'restartPolicy': json['restartPolicy'] == null ? undefined : V1ContainerRestartPolicyFromJSON(json['restartPolicy']),
        'restartPolicyRules': json['restartPolicyRules'] == null ? undefined : ((json['restartPolicyRules'] as Array<any>).map(V1ContainerRestartRuleFromJSON)),
        'securityContext': json['securityContext'] == null ? undefined : V1SecurityContextFromJSON(json['securityContext']),
        'startupProbe': json['startupProbe'] == null ? undefined : V1ProbeFromJSON(json['startupProbe']),
        'stdin': json['stdin'] == null ? undefined : json['stdin'],
        'stdinOnce': json['stdinOnce'] == null ? undefined : json['stdinOnce'],
        'terminationMessagePath': json['terminationMessagePath'] == null ? undefined : json['terminationMessagePath'],
        'terminationMessagePolicy': json['terminationMessagePolicy'] == null ? undefined : V1TerminationMessagePolicyFromJSON(json['terminationMessagePolicy']),
        'tty': json['tty'] == null ? undefined : json['tty'],
        'volumeDevices': json['volumeDevices'] == null ? undefined : ((json['volumeDevices'] as Array<any>).map(V1VolumeDeviceFromJSON)),
        'volumeMounts': json['volumeMounts'] == null ? undefined : ((json['volumeMounts'] as Array<any>).map(V1VolumeMountFromJSON)),
        'workingDir': json['workingDir'] == null ? undefined : json['workingDir'],
    };
}

export function V1ContainerToJSON(json: any): V1Container {
    return V1ContainerToJSONTyped(json, false);
}

export function V1ContainerToJSONTyped(value?: V1Container | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'args': value['args'],
        'command': value['command'],
        'env': value['env'] == null ? undefined : ((value['env'] as Array<any>).map(V1EnvVarToJSON)),
        'envFrom': value['envFrom'] == null ? undefined : ((value['envFrom'] as Array<any>).map(V1EnvFromSourceToJSON)),
        'image': value['image'],
        'imagePullPolicy': V1PullPolicyToJSON(value['imagePullPolicy']),
        'lifecycle': V1LifecycleToJSON(value['lifecycle']),
        'livenessProbe': V1ProbeToJSON(value['livenessProbe']),
        'name': value['name'],
        'ports': value['ports'] == null ? undefined : ((value['ports'] as Array<any>).map(V1ContainerPortToJSON)),
        'readinessProbe': V1ProbeToJSON(value['readinessProbe']),
        'resizePolicy': value['resizePolicy'] == null ? undefined : ((value['resizePolicy'] as Array<any>).map(V1ContainerResizePolicyToJSON)),
        'resources': V1ResourceRequirementsToJSON(value['resources']),
        'restartPolicy': V1ContainerRestartPolicyToJSON(value['restartPolicy']),
        'restartPolicyRules': value['restartPolicyRules'] == null ? undefined : ((value['restartPolicyRules'] as Array<any>).map(V1ContainerRestartRuleToJSON)),
        'securityContext': V1SecurityContextToJSON(value['securityContext']),
        'startupProbe': V1ProbeToJSON(value['startupProbe']),
        'stdin': value['stdin'],
        'stdinOnce': value['stdinOnce'],
        'terminationMessagePath': value['terminationMessagePath'],
        'terminationMessagePolicy': V1TerminationMessagePolicyToJSON(value['terminationMessagePolicy']),
        'tty': value['tty'],
        'volumeDevices': value['volumeDevices'] == null ? undefined : ((value['volumeDevices'] as Array<any>).map(V1VolumeDeviceToJSON)),
        'volumeMounts': value['volumeMounts'] == null ? undefined : ((value['volumeMounts'] as Array<any>).map(V1VolumeMountToJSON)),
        'workingDir': value['workingDir'],
    };
}

