/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1DownwardAPIVolumeFile } from './V1DownwardAPIVolumeFile';
import {
    V1DownwardAPIVolumeFileFromJSON,
    V1DownwardAPIVolumeFileFromJSONTyped,
    V1DownwardAPIVolumeFileToJSON,
    V1DownwardAPIVolumeFileToJSONTyped,
} from './V1DownwardAPIVolumeFile';

/**
 * 
 * @export
 * @interface V1DownwardAPIProjection
 */
export interface V1DownwardAPIProjection {
    /**
     * Items is a list of DownwardAPIVolume file
     * +optional
     * +listType=atomic
     * @type {Array<V1DownwardAPIVolumeFile>}
     * @memberof V1DownwardAPIProjection
     */
    items?: Array<V1DownwardAPIVolumeFile>;
}

/**
 * Check if a given object implements the V1DownwardAPIProjection interface.
 */
export function instanceOfV1DownwardAPIProjection(value: object): value is V1DownwardAPIProjection {
    return true;
}

export function V1DownwardAPIProjectionFromJSON(json: any): V1DownwardAPIProjection {
    return V1DownwardAPIProjectionFromJSONTyped(json, false);
}

export function V1DownwardAPIProjectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1DownwardAPIProjection {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(V1DownwardAPIVolumeFileFromJSON)),
    };
}

export function V1DownwardAPIProjectionToJSON(json: any): V1DownwardAPIProjection {
    return V1DownwardAPIProjectionToJSONTyped(json, false);
}

export function V1DownwardAPIProjectionToJSONTyped(value?: V1DownwardAPIProjection | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(V1DownwardAPIVolumeFileToJSON)),
    };
}

