/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1LocalObjectReference } from './V1LocalObjectReference';
import {
    V1LocalObjectReferenceFromJSON,
    V1LocalObjectReferenceFromJSONTyped,
    V1LocalObjectReferenceToJSON,
    V1LocalObjectReferenceToJSONTyped,
} from './V1LocalObjectReference';

/**
 * 
 * @export
 * @interface V1FlexVolumeSource
 */
export interface V1FlexVolumeSource {
    /**
     * driver is the name of the driver to use for this volume.
     * @type {string}
     * @memberof V1FlexVolumeSource
     */
    driver?: string;
    /**
     * fsType is the filesystem type to mount.
     * Must be a filesystem type supported by the host operating system.
     * Ex. "ext4", "xfs", "ntfs". The default filesystem depends on FlexVolume script.
     * +optional
     * @type {string}
     * @memberof V1FlexVolumeSource
     */
    fsType?: string;
    /**
     * options is Optional: this field holds extra command options if any.
     * +optional
     * @type {{ [key: string]: string; }}
     * @memberof V1FlexVolumeSource
     */
    options?: { [key: string]: string; };
    /**
     * readOnly is Optional: defaults to false (read/write). ReadOnly here will force
     * the ReadOnly setting in VolumeMounts.
     * +optional
     * @type {boolean}
     * @memberof V1FlexVolumeSource
     */
    readOnly?: boolean;
    /**
     * secretRef is Optional: secretRef is reference to the secret object containing
     * sensitive information to pass to the plugin scripts. This may be
     * empty if no secret object is specified. If the secret object
     * contains more than one secret, all secrets are passed to the plugin
     * scripts.
     * +optional
     * @type {V1LocalObjectReference}
     * @memberof V1FlexVolumeSource
     */
    secretRef?: V1LocalObjectReference;
}

/**
 * Check if a given object implements the V1FlexVolumeSource interface.
 */
export function instanceOfV1FlexVolumeSource(value: object): value is V1FlexVolumeSource {
    return true;
}

export function V1FlexVolumeSourceFromJSON(json: any): V1FlexVolumeSource {
    return V1FlexVolumeSourceFromJSONTyped(json, false);
}

export function V1FlexVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1FlexVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'driver': json['driver'] == null ? undefined : json['driver'],
        'fsType': json['fsType'] == null ? undefined : json['fsType'],
        'options': json['options'] == null ? undefined : json['options'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
        'secretRef': json['secretRef'] == null ? undefined : V1LocalObjectReferenceFromJSON(json['secretRef']),
    };
}

export function V1FlexVolumeSourceToJSON(json: any): V1FlexVolumeSource {
    return V1FlexVolumeSourceToJSONTyped(json, false);
}

export function V1FlexVolumeSourceToJSONTyped(value?: V1FlexVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'driver': value['driver'],
        'fsType': value['fsType'],
        'options': value['options'],
        'readOnly': value['readOnly'],
        'secretRef': V1LocalObjectReferenceToJSON(value['secretRef']),
    };
}

