/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1GCEPersistentDiskVolumeSource
 */
export interface V1GCEPersistentDiskVolumeSource {
    /**
     * fsType is filesystem type of the volume that you want to mount.
     * Tip: Ensure that the filesystem type is supported by the host operating system.
     * Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     * More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk
     * TODO: how do we prevent errors in the filesystem from compromising the machine
     * +optional
     * @type {string}
     * @memberof V1GCEPersistentDiskVolumeSource
     */
    fsType?: string;
    /**
     * partition is the partition in the volume that you want to mount.
     * If omitted, the default is to mount by volume name.
     * Examples: For volume /dev/sda1, you specify the partition as "1".
     * Similarly, the volume partition for /dev/sda is "0" (or you can leave the property empty).
     * More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk
     * +optional
     * @type {number}
     * @memberof V1GCEPersistentDiskVolumeSource
     */
    partition?: number;
    /**
     * pdName is unique name of the PD resource in GCE. Used to identify the disk in GCE.
     * More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk
     * @type {string}
     * @memberof V1GCEPersistentDiskVolumeSource
     */
    pdName?: string;
    /**
     * readOnly here will force the ReadOnly setting in VolumeMounts.
     * Defaults to false.
     * More info: https://kubernetes.io/docs/concepts/storage/volumes#gcepersistentdisk
     * +optional
     * @type {boolean}
     * @memberof V1GCEPersistentDiskVolumeSource
     */
    readOnly?: boolean;
}

/**
 * Check if a given object implements the V1GCEPersistentDiskVolumeSource interface.
 */
export function instanceOfV1GCEPersistentDiskVolumeSource(value: object): value is V1GCEPersistentDiskVolumeSource {
    return true;
}

export function V1GCEPersistentDiskVolumeSourceFromJSON(json: any): V1GCEPersistentDiskVolumeSource {
    return V1GCEPersistentDiskVolumeSourceFromJSONTyped(json, false);
}

export function V1GCEPersistentDiskVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1GCEPersistentDiskVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'fsType': json['fsType'] == null ? undefined : json['fsType'],
        'partition': json['partition'] == null ? undefined : json['partition'],
        'pdName': json['pdName'] == null ? undefined : json['pdName'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
    };
}

export function V1GCEPersistentDiskVolumeSourceToJSON(json: any): V1GCEPersistentDiskVolumeSource {
    return V1GCEPersistentDiskVolumeSourceToJSONTyped(json, false);
}

export function V1GCEPersistentDiskVolumeSourceToJSONTyped(value?: V1GCEPersistentDiskVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fsType': value['fsType'],
        'partition': value['partition'],
        'pdName': value['pdName'],
        'readOnly': value['readOnly'],
    };
}

