/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1HostAlias
 */
export interface V1HostAlias {
    /**
     * Hostnames for the above IP address.
     * +listType=atomic
     * @type {Array<string>}
     * @memberof V1HostAlias
     */
    hostnames?: Array<string>;
    /**
     * IP address of the host file entry.
     * +required
     * @type {string}
     * @memberof V1HostAlias
     */
    ip?: string;
}

/**
 * Check if a given object implements the V1HostAlias interface.
 */
export function instanceOfV1HostAlias(value: object): value is V1HostAlias {
    return true;
}

export function V1HostAliasFromJSON(json: any): V1HostAlias {
    return V1HostAliasFromJSONTyped(json, false);
}

export function V1HostAliasFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HostAlias {
    if (json == null) {
        return json;
    }
    return {
        
        'hostnames': json['hostnames'] == null ? undefined : json['hostnames'],
        'ip': json['ip'] == null ? undefined : json['ip'],
    };
}

export function V1HostAliasToJSON(json: any): V1HostAlias {
    return V1HostAliasToJSONTyped(json, false);
}

export function V1HostAliasToJSONTyped(value?: V1HostAlias | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'hostnames': value['hostnames'],
        'ip': value['ip'],
    };
}

