/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1HTTPHeader
 */
export interface V1HTTPHeader {
    /**
     * The header field name.
     * This will be canonicalized upon output, so case-variant names will be understood as the same header.
     * @type {string}
     * @memberof V1HTTPHeader
     */
    name?: string;
    /**
     * The header field value
     * @type {string}
     * @memberof V1HTTPHeader
     */
    value?: string;
}

/**
 * Check if a given object implements the V1HTTPHeader interface.
 */
export function instanceOfV1HTTPHeader(value: object): value is V1HTTPHeader {
    return true;
}

export function V1HTTPHeaderFromJSON(json: any): V1HTTPHeader {
    return V1HTTPHeaderFromJSONTyped(json, false);
}

export function V1HTTPHeaderFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1HTTPHeader {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function V1HTTPHeaderToJSON(json: any): V1HTTPHeader {
    return V1HTTPHeaderToJSONTyped(json, false);
}

export function V1HTTPHeaderToJSONTyped(value?: V1HTTPHeader | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
    };
}

