/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PullPolicy } from './V1PullPolicy';
import {
    V1PullPolicyFromJSON,
    V1PullPolicyFromJSONTyped,
    V1PullPolicyToJSON,
    V1PullPolicyToJSONTyped,
} from './V1PullPolicy';

/**
 * 
 * @export
 * @interface V1ImageVolumeSource
 */
export interface V1ImageVolumeSource {
    /**
     * Policy for pulling OCI objects. Possible values are:
     * Always: the kubelet always attempts to pull the reference. Container creation will fail If the pull fails.
     * Never: the kubelet never pulls the reference and only uses a local image or artifact. Container creation will fail if the reference isn't present.
     * IfNotPresent: the kubelet pulls if the reference isn't already present on disk. Container creation will fail if the reference isn't present and the pull fails.
     * Defaults to Always if :latest tag is specified, or IfNotPresent otherwise.
     * +optional
     * @type {V1PullPolicy}
     * @memberof V1ImageVolumeSource
     */
    pullPolicy?: V1PullPolicy;
    /**
     * Required: Image or artifact reference to be used.
     * Behaves in the same way as pod.spec.containers[*].image.
     * Pull secrets will be assembled in the same way as for the container image by looking up node credentials, SA image pull secrets, and pod spec image pull secrets.
     * More info: https://kubernetes.io/docs/concepts/containers/images
     * This field is optional to allow higher level config management to default or override
     * container images in workload controllers like Deployments and StatefulSets.
     * +optional
     * @type {string}
     * @memberof V1ImageVolumeSource
     */
    reference?: string;
}



/**
 * Check if a given object implements the V1ImageVolumeSource interface.
 */
export function instanceOfV1ImageVolumeSource(value: object): value is V1ImageVolumeSource {
    return true;
}

export function V1ImageVolumeSourceFromJSON(json: any): V1ImageVolumeSource {
    return V1ImageVolumeSourceFromJSONTyped(json, false);
}

export function V1ImageVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ImageVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'pullPolicy': json['pullPolicy'] == null ? undefined : V1PullPolicyFromJSON(json['pullPolicy']),
        'reference': json['reference'] == null ? undefined : json['reference'],
    };
}

export function V1ImageVolumeSourceToJSON(json: any): V1ImageVolumeSource {
    return V1ImageVolumeSourceToJSONTyped(json, false);
}

export function V1ImageVolumeSourceToJSONTyped(value?: V1ImageVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pullPolicy': V1PullPolicyToJSON(value['pullPolicy']),
        'reference': value['reference'],
    };
}

