/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1ObjectMeta } from './V1ObjectMeta';
import {
    V1ObjectMetaFromJSON,
    V1ObjectMetaFromJSONTyped,
    V1ObjectMetaToJSON,
    V1ObjectMetaToJSONTyped,
} from './V1ObjectMeta';
import type { V1PersistentVolumeClaimSpec } from './V1PersistentVolumeClaimSpec';
import {
    V1PersistentVolumeClaimSpecFromJSON,
    V1PersistentVolumeClaimSpecFromJSONTyped,
    V1PersistentVolumeClaimSpecToJSON,
    V1PersistentVolumeClaimSpecToJSONTyped,
} from './V1PersistentVolumeClaimSpec';

/**
 * 
 * @export
 * @interface V1PersistentVolumeClaimTemplate
 */
export interface V1PersistentVolumeClaimTemplate {
    /**
     * May contain labels and annotations that will be copied into the PVC
     * when creating it. No other fields are allowed and will be rejected during
     * validation.
     * 
     * +optional
     * @type {V1ObjectMeta}
     * @memberof V1PersistentVolumeClaimTemplate
     */
    metadata?: V1ObjectMeta;
    /**
     * The specification for the PersistentVolumeClaim. The entire content is
     * copied unchanged into the PVC that gets created from this
     * template. The same fields as in a PersistentVolumeClaim
     * are also valid here.
     * @type {V1PersistentVolumeClaimSpec}
     * @memberof V1PersistentVolumeClaimTemplate
     */
    spec?: V1PersistentVolumeClaimSpec;
}

/**
 * Check if a given object implements the V1PersistentVolumeClaimTemplate interface.
 */
export function instanceOfV1PersistentVolumeClaimTemplate(value: object): value is V1PersistentVolumeClaimTemplate {
    return true;
}

export function V1PersistentVolumeClaimTemplateFromJSON(json: any): V1PersistentVolumeClaimTemplate {
    return V1PersistentVolumeClaimTemplateFromJSONTyped(json, false);
}

export function V1PersistentVolumeClaimTemplateFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PersistentVolumeClaimTemplate {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : V1ObjectMetaFromJSON(json['metadata']),
        'spec': json['spec'] == null ? undefined : V1PersistentVolumeClaimSpecFromJSON(json['spec']),
    };
}

export function V1PersistentVolumeClaimTemplateToJSON(json: any): V1PersistentVolumeClaimTemplate {
    return V1PersistentVolumeClaimTemplateToJSONTyped(json, false);
}

export function V1PersistentVolumeClaimTemplateToJSONTyped(value?: V1PersistentVolumeClaimTemplate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': V1ObjectMetaToJSON(value['metadata']),
        'spec': V1PersistentVolumeClaimSpecToJSON(value['spec']),
    };
}

