/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PersistentVolumeClaimVolumeSource
 */
export interface V1PersistentVolumeClaimVolumeSource {
    /**
     * claimName is the name of a PersistentVolumeClaim in the same namespace as the pod using this volume.
     * More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#persistentvolumeclaims
     * @type {string}
     * @memberof V1PersistentVolumeClaimVolumeSource
     */
    claimName?: string;
    /**
     * readOnly Will force the ReadOnly setting in VolumeMounts.
     * Default false.
     * +optional
     * @type {boolean}
     * @memberof V1PersistentVolumeClaimVolumeSource
     */
    readOnly?: boolean;
}

/**
 * Check if a given object implements the V1PersistentVolumeClaimVolumeSource interface.
 */
export function instanceOfV1PersistentVolumeClaimVolumeSource(value: object): value is V1PersistentVolumeClaimVolumeSource {
    return true;
}

export function V1PersistentVolumeClaimVolumeSourceFromJSON(json: any): V1PersistentVolumeClaimVolumeSource {
    return V1PersistentVolumeClaimVolumeSourceFromJSONTyped(json, false);
}

export function V1PersistentVolumeClaimVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PersistentVolumeClaimVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'claimName': json['claimName'] == null ? undefined : json['claimName'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
    };
}

export function V1PersistentVolumeClaimVolumeSourceToJSON(json: any): V1PersistentVolumeClaimVolumeSource {
    return V1PersistentVolumeClaimVolumeSourceToJSONTyped(json, false);
}

export function V1PersistentVolumeClaimVolumeSourceToJSONTyped(value?: V1PersistentVolumeClaimVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'claimName': value['claimName'],
        'readOnly': value['readOnly'],
    };
}

