/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1PersistentVolumeAccessMode } from './V1PersistentVolumeAccessMode';
import {
    V1PersistentVolumeAccessModeFromJSON,
    V1PersistentVolumeAccessModeFromJSONTyped,
    V1PersistentVolumeAccessModeToJSON,
    V1PersistentVolumeAccessModeToJSONTyped,
} from './V1PersistentVolumeAccessMode';
import type { V1TypedLocalObjectReference } from './V1TypedLocalObjectReference';
import {
    V1TypedLocalObjectReferenceFromJSON,
    V1TypedLocalObjectReferenceFromJSONTyped,
    V1TypedLocalObjectReferenceToJSON,
    V1TypedLocalObjectReferenceToJSONTyped,
} from './V1TypedLocalObjectReference';
import type { V1PersistentVolumeMode } from './V1PersistentVolumeMode';
import {
    V1PersistentVolumeModeFromJSON,
    V1PersistentVolumeModeFromJSONTyped,
    V1PersistentVolumeModeToJSON,
    V1PersistentVolumeModeToJSONTyped,
} from './V1PersistentVolumeMode';
import type { V1LabelSelector } from './V1LabelSelector';
import {
    V1LabelSelectorFromJSON,
    V1LabelSelectorFromJSONTyped,
    V1LabelSelectorToJSON,
    V1LabelSelectorToJSONTyped,
} from './V1LabelSelector';
import type { V1VolumeResourceRequirements } from './V1VolumeResourceRequirements';
import {
    V1VolumeResourceRequirementsFromJSON,
    V1VolumeResourceRequirementsFromJSONTyped,
    V1VolumeResourceRequirementsToJSON,
    V1VolumeResourceRequirementsToJSONTyped,
} from './V1VolumeResourceRequirements';
import type { V1TypedObjectReference } from './V1TypedObjectReference';
import {
    V1TypedObjectReferenceFromJSON,
    V1TypedObjectReferenceFromJSONTyped,
    V1TypedObjectReferenceToJSON,
    V1TypedObjectReferenceToJSONTyped,
} from './V1TypedObjectReference';

/**
 * 
 * @export
 * @interface V1PersistentVolumeClaimSpec
 */
export interface V1PersistentVolumeClaimSpec {
    /**
     * accessModes contains the desired access modes the volume should have.
     * More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1
     * +optional
     * +listType=atomic
     * @type {Array<V1PersistentVolumeAccessMode>}
     * @memberof V1PersistentVolumeClaimSpec
     */
    accessModes?: Array<V1PersistentVolumeAccessMode>;
    /**
     * dataSource field can be used to specify either:
     * * An existing VolumeSnapshot object (snapshot.storage.k8s.io/VolumeSnapshot)
     * * An existing PVC (PersistentVolumeClaim)
     * If the provisioner or an external controller can support the specified data source,
     * it will create a new volume based on the contents of the specified data source.
     * When the AnyVolumeDataSource feature gate is enabled, dataSource contents will be copied to dataSourceRef,
     * and dataSourceRef contents will be copied to dataSource when dataSourceRef.namespace is not specified.
     * If the namespace is specified, then dataSourceRef will not be copied to dataSource.
     * +optional
     * @type {V1TypedLocalObjectReference}
     * @memberof V1PersistentVolumeClaimSpec
     */
    dataSource?: V1TypedLocalObjectReference;
    /**
     * dataSourceRef specifies the object from which to populate the volume with data, if a non-empty
     * volume is desired. This may be any object from a non-empty API group (non
     * core object) or a PersistentVolumeClaim object.
     * When this field is specified, volume binding will only succeed if the type of
     * the specified object matches some installed volume populator or dynamic
     * provisioner.
     * This field will replace the functionality of the dataSource field and as such
     * if both fields are non-empty, they must have the same value. For backwards
     * compatibility, when namespace isn't specified in dataSourceRef,
     * both fields (dataSource and dataSourceRef) will be set to the same
     * value automatically if one of them is empty and the other is non-empty.
     * When namespace is specified in dataSourceRef,
     * dataSource isn't set to the same value and must be empty.
     * There are three important differences between dataSource and dataSourceRef:
     * * While dataSource only allows two specific types of objects, dataSourceRef
     *   allows any non-core object, as well as PersistentVolumeClaim objects.
     * * While dataSource ignores disallowed values (dropping them), dataSourceRef
     *   preserves all values, and generates an error if a disallowed value is
     *   specified.
     * * While dataSource only allows local objects, dataSourceRef allows objects
     *   in any namespaces.
     * (Beta) Using this field requires the AnyVolumeDataSource feature gate to be enabled.
     * (Alpha) Using the namespace field of dataSourceRef requires the CrossNamespaceVolumeDataSource feature gate to be enabled.
     * +optional
     * @type {V1TypedObjectReference}
     * @memberof V1PersistentVolumeClaimSpec
     */
    dataSourceRef?: V1TypedObjectReference;
    /**
     * resources represents the minimum resources the volume should have.
     * Users are allowed to specify resource requirements
     * that are lower than previous value but must still be higher than capacity recorded in the
     * status field of the claim.
     * More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#resources
     * +optional
     * @type {V1VolumeResourceRequirements}
     * @memberof V1PersistentVolumeClaimSpec
     */
    resources?: V1VolumeResourceRequirements;
    /**
     * selector is a label query over volumes to consider for binding.
     * +optional
     * @type {V1LabelSelector}
     * @memberof V1PersistentVolumeClaimSpec
     */
    selector?: V1LabelSelector;
    /**
     * storageClassName is the name of the StorageClass required by the claim.
     * More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1
     * +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimSpec
     */
    storageClassName?: string;
    /**
     * volumeAttributesClassName may be used to set the VolumeAttributesClass used by this claim.
     * If specified, the CSI driver will create or update the volume with the attributes defined
     * in the corresponding VolumeAttributesClass. This has a different purpose than storageClassName,
     * it can be changed after the claim is created. An empty string or nil value indicates that no
     * VolumeAttributesClass will be applied to the claim. If the claim enters an Infeasible error state,
     * this field can be reset to its previous value (including nil) to cancel the modification.
     * If the resource referred to by volumeAttributesClass does not exist, this PersistentVolumeClaim will be
     * set to a Pending state, as reflected by the modifyVolumeStatus field, until such as a resource
     * exists.
     * More info: https://kubernetes.io/docs/concepts/storage/volume-attributes-classes/
     * +featureGate=VolumeAttributesClass
     * +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimSpec
     */
    volumeAttributesClassName?: string;
    /**
     * volumeMode defines what type of volume is required by the claim.
     * Value of Filesystem is implied when not included in claim spec.
     * +optional
     * @type {V1PersistentVolumeMode}
     * @memberof V1PersistentVolumeClaimSpec
     */
    volumeMode?: V1PersistentVolumeMode;
    /**
     * volumeName is the binding reference to the PersistentVolume backing this claim.
     * +optional
     * @type {string}
     * @memberof V1PersistentVolumeClaimSpec
     */
    volumeName?: string;
}



/**
 * Check if a given object implements the V1PersistentVolumeClaimSpec interface.
 */
export function instanceOfV1PersistentVolumeClaimSpec(value: object): value is V1PersistentVolumeClaimSpec {
    return true;
}

export function V1PersistentVolumeClaimSpecFromJSON(json: any): V1PersistentVolumeClaimSpec {
    return V1PersistentVolumeClaimSpecFromJSONTyped(json, false);
}

export function V1PersistentVolumeClaimSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PersistentVolumeClaimSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'accessModes': json['accessModes'] == null ? undefined : ((json['accessModes'] as Array<any>).map(V1PersistentVolumeAccessModeFromJSON)),
        'dataSource': json['dataSource'] == null ? undefined : V1TypedLocalObjectReferenceFromJSON(json['dataSource']),
        'dataSourceRef': json['dataSourceRef'] == null ? undefined : V1TypedObjectReferenceFromJSON(json['dataSourceRef']),
        'resources': json['resources'] == null ? undefined : V1VolumeResourceRequirementsFromJSON(json['resources']),
        'selector': json['selector'] == null ? undefined : V1LabelSelectorFromJSON(json['selector']),
        'storageClassName': json['storageClassName'] == null ? undefined : json['storageClassName'],
        'volumeAttributesClassName': json['volumeAttributesClassName'] == null ? undefined : json['volumeAttributesClassName'],
        'volumeMode': json['volumeMode'] == null ? undefined : V1PersistentVolumeModeFromJSON(json['volumeMode']),
        'volumeName': json['volumeName'] == null ? undefined : json['volumeName'],
    };
}

export function V1PersistentVolumeClaimSpecToJSON(json: any): V1PersistentVolumeClaimSpec {
    return V1PersistentVolumeClaimSpecToJSONTyped(json, false);
}

export function V1PersistentVolumeClaimSpecToJSONTyped(value?: V1PersistentVolumeClaimSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessModes': value['accessModes'] == null ? undefined : ((value['accessModes'] as Array<any>).map(V1PersistentVolumeAccessModeToJSON)),
        'dataSource': V1TypedLocalObjectReferenceToJSON(value['dataSource']),
        'dataSourceRef': V1TypedObjectReferenceToJSON(value['dataSourceRef']),
        'resources': V1VolumeResourceRequirementsToJSON(value['resources']),
        'selector': V1LabelSelectorToJSON(value['selector']),
        'storageClassName': value['storageClassName'],
        'volumeAttributesClassName': value['volumeAttributesClassName'],
        'volumeMode': V1PersistentVolumeModeToJSON(value['volumeMode']),
        'volumeName': value['volumeName'],
    };
}

