/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1OSName } from './V1OSName';
import {
    V1OSNameFromJSON,
    V1OSNameFromJSONTyped,
    V1OSNameToJSON,
    V1OSNameToJSONTyped,
} from './V1OSName';

/**
 * 
 * @export
 * @interface V1PodOS
 */
export interface V1PodOS {
    /**
     * Name is the name of the operating system. The currently supported values are linux and windows.
     * Additional value may be defined in future and can be one of:
     * https://github.com/opencontainers/runtime-spec/blob/master/config.md#platform-specific-configuration
     * Clients should expect to handle additional values and treat unrecognized values in this field as os: null
     * @type {V1OSName}
     * @memberof V1PodOS
     */
    name?: V1OSName;
}



/**
 * Check if a given object implements the V1PodOS interface.
 */
export function instanceOfV1PodOS(value: object): value is V1PodOS {
    return true;
}

export function V1PodOSFromJSON(json: any): V1PodOS {
    return V1PodOSFromJSONTyped(json, false);
}

export function V1PodOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PodOS {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : V1OSNameFromJSON(json['name']),
    };
}

export function V1PodOSToJSON(json: any): V1PodOS {
    return V1PodOSToJSONTyped(json, false);
}

export function V1PodOSToJSONTyped(value?: V1PodOS | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': V1OSNameToJSON(value['name']),
    };
}

