/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1DNSPolicy } from './V1DNSPolicy';
import {
    V1DNSPolicyFromJSON,
    V1DNSPolicyFromJSONTyped,
    V1DNSPolicyToJSON,
    V1DNSPolicyToJSONTyped,
} from './V1DNSPolicy';
import type { V1TopologySpreadConstraint } from './V1TopologySpreadConstraint';
import {
    V1TopologySpreadConstraintFromJSON,
    V1TopologySpreadConstraintFromJSONTyped,
    V1TopologySpreadConstraintToJSON,
    V1TopologySpreadConstraintToJSONTyped,
} from './V1TopologySpreadConstraint';
import type { V1HostAlias } from './V1HostAlias';
import {
    V1HostAliasFromJSON,
    V1HostAliasFromJSONTyped,
    V1HostAliasToJSON,
    V1HostAliasToJSONTyped,
} from './V1HostAlias';
import type { V1PodDNSConfig } from './V1PodDNSConfig';
import {
    V1PodDNSConfigFromJSON,
    V1PodDNSConfigFromJSONTyped,
    V1PodDNSConfigToJSON,
    V1PodDNSConfigToJSONTyped,
} from './V1PodDNSConfig';
import type { V1WorkloadReference } from './V1WorkloadReference';
import {
    V1WorkloadReferenceFromJSON,
    V1WorkloadReferenceFromJSONTyped,
    V1WorkloadReferenceToJSON,
    V1WorkloadReferenceToJSONTyped,
} from './V1WorkloadReference';
import type { V1PodReadinessGate } from './V1PodReadinessGate';
import {
    V1PodReadinessGateFromJSON,
    V1PodReadinessGateFromJSONTyped,
    V1PodReadinessGateToJSON,
    V1PodReadinessGateToJSONTyped,
} from './V1PodReadinessGate';
import type { V1PreemptionPolicy } from './V1PreemptionPolicy';
import {
    V1PreemptionPolicyFromJSON,
    V1PreemptionPolicyFromJSONTyped,
    V1PreemptionPolicyToJSON,
    V1PreemptionPolicyToJSONTyped,
} from './V1PreemptionPolicy';
import type { V1PodSecurityContext } from './V1PodSecurityContext';
import {
    V1PodSecurityContextFromJSON,
    V1PodSecurityContextFromJSONTyped,
    V1PodSecurityContextToJSON,
    V1PodSecurityContextToJSONTyped,
} from './V1PodSecurityContext';
import type { V1Container } from './V1Container';
import {
    V1ContainerFromJSON,
    V1ContainerFromJSONTyped,
    V1ContainerToJSON,
    V1ContainerToJSONTyped,
} from './V1Container';
import type { V1PodResourceClaim } from './V1PodResourceClaim';
import {
    V1PodResourceClaimFromJSON,
    V1PodResourceClaimFromJSONTyped,
    V1PodResourceClaimToJSON,
    V1PodResourceClaimToJSONTyped,
} from './V1PodResourceClaim';
import type { V1Toleration } from './V1Toleration';
import {
    V1TolerationFromJSON,
    V1TolerationFromJSONTyped,
    V1TolerationToJSON,
    V1TolerationToJSONTyped,
} from './V1Toleration';
import type { V1RestartPolicy } from './V1RestartPolicy';
import {
    V1RestartPolicyFromJSON,
    V1RestartPolicyFromJSONTyped,
    V1RestartPolicyToJSON,
    V1RestartPolicyToJSONTyped,
} from './V1RestartPolicy';
import type { V1Volume } from './V1Volume';
import {
    V1VolumeFromJSON,
    V1VolumeFromJSONTyped,
    V1VolumeToJSON,
    V1VolumeToJSONTyped,
} from './V1Volume';
import type { ResourceQuantity } from './ResourceQuantity';
import {
    ResourceQuantityFromJSON,
    ResourceQuantityFromJSONTyped,
    ResourceQuantityToJSON,
    ResourceQuantityToJSONTyped,
} from './ResourceQuantity';
import type { V1Affinity } from './V1Affinity';
import {
    V1AffinityFromJSON,
    V1AffinityFromJSONTyped,
    V1AffinityToJSON,
    V1AffinityToJSONTyped,
} from './V1Affinity';
import type { V1LocalObjectReference } from './V1LocalObjectReference';
import {
    V1LocalObjectReferenceFromJSON,
    V1LocalObjectReferenceFromJSONTyped,
    V1LocalObjectReferenceToJSON,
    V1LocalObjectReferenceToJSONTyped,
} from './V1LocalObjectReference';
import type { V1PodSchedulingGate } from './V1PodSchedulingGate';
import {
    V1PodSchedulingGateFromJSON,
    V1PodSchedulingGateFromJSONTyped,
    V1PodSchedulingGateToJSON,
    V1PodSchedulingGateToJSONTyped,
} from './V1PodSchedulingGate';
import type { V1EphemeralContainer } from './V1EphemeralContainer';
import {
    V1EphemeralContainerFromJSON,
    V1EphemeralContainerFromJSONTyped,
    V1EphemeralContainerToJSON,
    V1EphemeralContainerToJSONTyped,
} from './V1EphemeralContainer';
import type { V1PodOS } from './V1PodOS';
import {
    V1PodOSFromJSON,
    V1PodOSFromJSONTyped,
    V1PodOSToJSON,
    V1PodOSToJSONTyped,
} from './V1PodOS';
import type { V1ResourceRequirements } from './V1ResourceRequirements';
import {
    V1ResourceRequirementsFromJSON,
    V1ResourceRequirementsFromJSONTyped,
    V1ResourceRequirementsToJSON,
    V1ResourceRequirementsToJSONTyped,
} from './V1ResourceRequirements';

/**
 * 
 * @export
 * @interface V1PodSpec
 */
export interface V1PodSpec {
    /**
     * Optional duration in seconds the pod may be active on the node relative to
     * StartTime before the system will actively try to mark it failed and kill associated containers.
     * Value must be a positive integer.
     * +optional
     * @type {number}
     * @memberof V1PodSpec
     */
    activeDeadlineSeconds?: number;
    /**
     * If specified, the pod's scheduling constraints
     * +optional
     * @type {V1Affinity}
     * @memberof V1PodSpec
     */
    affinity?: V1Affinity;
    /**
     * AutomountServiceAccountToken indicates whether a service account token should be automatically mounted.
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    automountServiceAccountToken?: boolean;
    /**
     * List of containers belonging to the pod.
     * Containers cannot currently be added or removed.
     * There must be at least one container in a Pod.
     * Cannot be updated.
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1Container>}
     * @memberof V1PodSpec
     */
    containers?: Array<V1Container>;
    /**
     * Specifies the DNS parameters of a pod.
     * Parameters specified here will be merged to the generated DNS
     * configuration based on DNSPolicy.
     * +optional
     * @type {V1PodDNSConfig}
     * @memberof V1PodSpec
     */
    dnsConfig?: V1PodDNSConfig;
    /**
     * Set DNS policy for the pod.
     * Defaults to "ClusterFirst".
     * Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
     * DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
     * To have DNS options set along with hostNetwork, you have to specify DNS policy
     * explicitly to 'ClusterFirstWithHostNet'.
     * +optional
     * @type {V1DNSPolicy}
     * @memberof V1PodSpec
     */
    dnsPolicy?: V1DNSPolicy;
    /**
     * EnableServiceLinks indicates whether information about services should be injected into pod's
     * environment variables, matching the syntax of Docker links.
     * Optional: Defaults to true.
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    enableServiceLinks?: boolean;
    /**
     * List of ephemeral containers run in this pod. Ephemeral containers may be run in an existing
     * pod to perform user-initiated actions such as debugging. This list cannot be specified when
     * creating a pod, and it cannot be modified by updating the pod spec. In order to add an
     * ephemeral container to an existing pod, use the pod's ephemeralcontainers subresource.
     * +optional
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1EphemeralContainer>}
     * @memberof V1PodSpec
     */
    ephemeralContainers?: Array<V1EphemeralContainer>;
    /**
     * HostAliases is an optional list of hosts and IPs that will be injected into the pod's hosts
     * file if specified.
     * +optional
     * +patchMergeKey=ip
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=ip
     * @type {Array<V1HostAlias>}
     * @memberof V1PodSpec
     */
    hostAliases?: Array<V1HostAlias>;
    /**
     * Use the host's ipc namespace.
     * Optional: Default to false.
     * +k8s:conversion-gen=false
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    hostIPC?: boolean;
    /**
     * Host networking requested for this pod. Use the host's network namespace.
     * When using HostNetwork you should specify ports so the scheduler is aware.
     * When `hostNetwork` is true, specified `hostPort` fields in port definitions must match `containerPort`,
     * and unspecified `hostPort` fields in port definitions are defaulted to match `containerPort`.
     * Default to false.
     * +k8s:conversion-gen=false
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    hostNetwork?: boolean;
    /**
     * Use the host's pid namespace.
     * Optional: Default to false.
     * +k8s:conversion-gen=false
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    hostPID?: boolean;
    /**
     * Use the host's user namespace.
     * Optional: Default to true.
     * If set to true or not present, the pod will be run in the host user namespace, useful
     * for when the pod needs a feature only available to the host user namespace, such as
     * loading a kernel module with CAP_SYS_MODULE.
     * When set to false, a new userns is created for the pod. Setting false is useful for
     * mitigating container breakout vulnerabilities even allowing users to run their
     * containers as root without actually having root privileges on the host.
     * This field is alpha-level and is only honored by servers that enable the UserNamespacesSupport feature.
     * +k8s:conversion-gen=false
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    hostUsers?: boolean;
    /**
     * Specifies the hostname of the Pod
     * If not specified, the pod's hostname will be set to a system-defined value.
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    hostname?: string;
    /**
     * HostnameOverride specifies an explicit override for the pod's hostname as perceived by the pod.
     * This field only specifies the pod's hostname and does not affect its DNS records.
     * When this field is set to a non-empty string:
     * - It takes precedence over the values set in `hostname` and `subdomain`.
     * - The Pod's hostname will be set to this value.
     * - `setHostnameAsFQDN` must be nil or set to false.
     * - `hostNetwork` must be set to false.
     * 
     * This field must be a valid DNS subdomain as defined in RFC 1123 and contain at most 64 characters.
     * Requires the HostnameOverride feature gate to be enabled.
     * 
     * +featureGate=HostnameOverride
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    hostnameOverride?: string;
    /**
     * ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec.
     * If specified, these secrets will be passed to individual puller implementations for them to use.
     * More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod
     * +optional
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1LocalObjectReference>}
     * @memberof V1PodSpec
     */
    imagePullSecrets?: Array<V1LocalObjectReference>;
    /**
     * List of initialization containers belonging to the pod.
     * Init containers are executed in order prior to containers being started. If any
     * init container fails, the pod is considered to have failed and is handled according
     * to its restartPolicy. The name for an init container or normal container must be
     * unique among all containers.
     * Init containers may not have Lifecycle actions, Readiness probes, Liveness probes, or Startup probes.
     * The resourceRequirements of an init container are taken into account during scheduling
     * by finding the highest request/limit for each resource type, and then using the max of
     * that value or the sum of the normal containers. Limits are applied to init containers
     * in a similar fashion.
     * Init containers cannot currently be added or removed.
     * Cannot be updated.
     * More info: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1Container>}
     * @memberof V1PodSpec
     */
    initContainers?: Array<V1Container>;
    /**
     * NodeName indicates in which node this pod is scheduled.
     * If empty, this pod is a candidate for scheduling by the scheduler defined in schedulerName.
     * Once this field is set, the kubelet for this node becomes responsible for the lifecycle of this pod.
     * This field should not be used to express a desire for the pod to be scheduled on a specific node.
     * https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#nodename
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    nodeName?: string;
    /**
     * NodeSelector is a selector which must be true for the pod to fit on a node.
     * Selector which must match a node's labels for the pod to be scheduled on that node.
     * More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
     * +optional
     * +mapType=atomic
     * @type {{ [key: string]: string; }}
     * @memberof V1PodSpec
     */
    nodeSelector?: { [key: string]: string; };
    /**
     * Specifies the OS of the containers in the pod.
     * Some pod and container fields are restricted if this is set.
     * 
     * If the OS field is set to linux, the following fields must be unset:
     * -securityContext.windowsOptions
     * 
     * If the OS field is set to windows, following fields must be unset:
     * - spec.hostPID
     * - spec.hostIPC
     * - spec.hostUsers
     * - spec.resources
     * - spec.securityContext.appArmorProfile
     * - spec.securityContext.seLinuxOptions
     * - spec.securityContext.seccompProfile
     * - spec.securityContext.fsGroup
     * - spec.securityContext.fsGroupChangePolicy
     * - spec.securityContext.sysctls
     * - spec.shareProcessNamespace
     * - spec.securityContext.runAsUser
     * - spec.securityContext.runAsGroup
     * - spec.securityContext.supplementalGroups
     * - spec.securityContext.supplementalGroupsPolicy
     * - spec.containers[*].securityContext.appArmorProfile
     * - spec.containers[*].securityContext.seLinuxOptions
     * - spec.containers[*].securityContext.seccompProfile
     * - spec.containers[*].securityContext.capabilities
     * - spec.containers[*].securityContext.readOnlyRootFilesystem
     * - spec.containers[*].securityContext.privileged
     * - spec.containers[*].securityContext.allowPrivilegeEscalation
     * - spec.containers[*].securityContext.procMount
     * - spec.containers[*].securityContext.runAsUser
     * - spec.containers[*].securityContext.runAsGroup
     * +optional
     * @type {V1PodOS}
     * @memberof V1PodSpec
     */
    os?: V1PodOS;
    /**
     * Overhead represents the resource overhead associated with running a pod for a given RuntimeClass.
     * This field will be autopopulated at admission time by the RuntimeClass admission controller. If
     * the RuntimeClass admission controller is enabled, overhead must not be set in Pod create requests.
     * The RuntimeClass admission controller will reject Pod create requests which have the overhead already
     * set. If RuntimeClass is configured and selected in the PodSpec, Overhead will be set to the value
     * defined in the corresponding RuntimeClass, otherwise it will remain unset and treated as zero.
     * More info: https://git.k8s.io/enhancements/keps/sig-node/688-pod-overhead/README.md
     * +optional
     * @type {{ [key: string]: ResourceQuantity; }}
     * @memberof V1PodSpec
     */
    overhead?: { [key: string]: ResourceQuantity; };
    /**
     * PreemptionPolicy is the Policy for preempting pods with lower priority.
     * One of Never, PreemptLowerPriority.
     * Defaults to PreemptLowerPriority if unset.
     * +optional
     * @type {V1PreemptionPolicy}
     * @memberof V1PodSpec
     */
    preemptionPolicy?: V1PreemptionPolicy;
    /**
     * The priority value. Various system components use this field to find the
     * priority of the pod. When Priority Admission Controller is enabled, it
     * prevents users from setting this field. The admission controller populates
     * this field from PriorityClassName.
     * The higher the value, the higher the priority.
     * +optional
     * @type {number}
     * @memberof V1PodSpec
     */
    priority?: number;
    /**
     * If specified, indicates the pod's priority. "system-node-critical" and
     * "system-cluster-critical" are two special keywords which indicate the
     * highest priorities with the former being the highest priority. Any other
     * name must be defined by creating a PriorityClass object with that name.
     * If not specified, the pod priority will be default or zero if there is no
     * default.
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    priorityClassName?: string;
    /**
     * If specified, all readiness gates will be evaluated for pod readiness.
     * A pod is ready when all its containers are ready AND
     * all conditions specified in the readiness gates have status equal to "True"
     * More info: https://git.k8s.io/enhancements/keps/sig-network/580-pod-readiness-gates
     * +optional
     * +listType=atomic
     * @type {Array<V1PodReadinessGate>}
     * @memberof V1PodSpec
     */
    readinessGates?: Array<V1PodReadinessGate>;
    /**
     * ResourceClaims defines which ResourceClaims must be allocated
     * and reserved before the Pod is allowed to start. The resources
     * will be made available to those containers which consume them
     * by name.
     * 
     * This is a stable field but requires that the
     * DynamicResourceAllocation feature gate is enabled.
     * 
     * This field is immutable.
     * 
     * +patchMergeKey=name
     * +patchStrategy=merge,retainKeys
     * +listType=map
     * +listMapKey=name
     * +featureGate=DynamicResourceAllocation
     * +optional
     * @type {Array<V1PodResourceClaim>}
     * @memberof V1PodSpec
     */
    resourceClaims?: Array<V1PodResourceClaim>;
    /**
     * Resources is the total amount of CPU and Memory resources required by all
     * containers in the pod. It supports specifying Requests and Limits for
     * "cpu", "memory" and "hugepages-" resource names only. ResourceClaims are not supported.
     * 
     * This field enables fine-grained control over resource allocation for the
     * entire pod, allowing resource sharing among containers in a pod.
     * TODO: For beta graduation, expand this comment with a detailed explanation.
     * 
     * This is an alpha field and requires enabling the PodLevelResources feature
     * gate.
     * 
     * +featureGate=PodLevelResources
     * +optional
     * @type {V1ResourceRequirements}
     * @memberof V1PodSpec
     */
    resources?: V1ResourceRequirements;
    /**
     * Restart policy for all containers within the pod.
     * One of Always, OnFailure, Never. In some contexts, only a subset of those values may be permitted.
     * Default to Always.
     * More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
     * +optional
     * @type {V1RestartPolicy}
     * @memberof V1PodSpec
     */
    restartPolicy?: V1RestartPolicy;
    /**
     * RuntimeClassName refers to a RuntimeClass object in the node.k8s.io group, which should be used
     * to run this pod.  If no RuntimeClass resource matches the named class, the pod will not be run.
     * If unset or empty, the "legacy" RuntimeClass will be used, which is an implicit class with an
     * empty definition that uses the default runtime handler.
     * More info: https://git.k8s.io/enhancements/keps/sig-node/585-runtime-class
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    runtimeClassName?: string;
    /**
     * If specified, the pod will be dispatched by specified scheduler.
     * If not specified, the pod will be dispatched by default scheduler.
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    schedulerName?: string;
    /**
     * SchedulingGates is an opaque list of values that if specified will block scheduling the pod.
     * If schedulingGates is not empty, the pod will stay in the SchedulingGated state and the
     * scheduler will not attempt to schedule the pod.
     * 
     * SchedulingGates can only be set at pod creation time, and be removed only afterwards.
     * 
     * +patchMergeKey=name
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=name
     * +optional
     * @type {Array<V1PodSchedulingGate>}
     * @memberof V1PodSpec
     */
    schedulingGates?: Array<V1PodSchedulingGate>;
    /**
     * SecurityContext holds pod-level security attributes and common container settings.
     * Optional: Defaults to empty.  See type description for default values of each field.
     * +optional
     * @type {V1PodSecurityContext}
     * @memberof V1PodSpec
     */
    securityContext?: V1PodSecurityContext;
    /**
     * DeprecatedServiceAccount is a deprecated alias for ServiceAccountName.
     * Deprecated: Use serviceAccountName instead.
     * +k8s:conversion-gen=false
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    serviceAccount?: string;
    /**
     * ServiceAccountName is the name of the ServiceAccount to use to run this pod.
     * More info: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    serviceAccountName?: string;
    /**
     * If true the pod's hostname will be configured as the pod's FQDN, rather than the leaf name (the default).
     * In Linux containers, this means setting the FQDN in the hostname field of the kernel (the nodename field of struct utsname).
     * In Windows containers, this means setting the registry value of hostname for the registry key HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\Tcpip\\Parameters to FQDN.
     * If a pod does not have FQDN, this has no effect.
     * Default to false.
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    setHostnameAsFQDN?: boolean;
    /**
     * Share a single process namespace between all of the containers in a pod.
     * When this is set containers will be able to view and signal processes from other containers
     * in the same pod, and the first process in each container will not be assigned PID 1.
     * HostPID and ShareProcessNamespace cannot both be set.
     * Optional: Default to false.
     * +k8s:conversion-gen=false
     * +optional
     * @type {boolean}
     * @memberof V1PodSpec
     */
    shareProcessNamespace?: boolean;
    /**
     * If specified, the fully qualified Pod hostname will be "<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>".
     * If not specified, the pod will not have a domainname at all.
     * +optional
     * @type {string}
     * @memberof V1PodSpec
     */
    subdomain?: string;
    /**
     * Optional duration in seconds the pod needs to terminate gracefully. May be decreased in delete request.
     * Value must be non-negative integer. The value zero indicates stop immediately via
     * the kill signal (no opportunity to shut down).
     * If this value is nil, the default grace period will be used instead.
     * The grace period is the duration in seconds after the processes running in the pod are sent
     * a termination signal and the time when the processes are forcibly halted with a kill signal.
     * Set this value longer than the expected cleanup time for your process.
     * Defaults to 30 seconds.
     * +optional
     * @type {number}
     * @memberof V1PodSpec
     */
    terminationGracePeriodSeconds?: number;
    /**
     * If specified, the pod's tolerations.
     * +optional
     * +listType=atomic
     * @type {Array<V1Toleration>}
     * @memberof V1PodSpec
     */
    tolerations?: Array<V1Toleration>;
    /**
     * TopologySpreadConstraints describes how a group of pods ought to spread across topology
     * domains. Scheduler will schedule pods in a way which abides by the constraints.
     * All topologySpreadConstraints are ANDed.
     * +optional
     * +patchMergeKey=topologyKey
     * +patchStrategy=merge
     * +listType=map
     * +listMapKey=topologyKey
     * +listMapKey=whenUnsatisfiable
     * @type {Array<V1TopologySpreadConstraint>}
     * @memberof V1PodSpec
     */
    topologySpreadConstraints?: Array<V1TopologySpreadConstraint>;
    /**
     * List of volumes that can be mounted by containers belonging to the pod.
     * More info: https://kubernetes.io/docs/concepts/storage/volumes
     * +optional
     * +patchMergeKey=name
     * +patchStrategy=merge,retainKeys
     * +listType=map
     * +listMapKey=name
     * @type {Array<V1Volume>}
     * @memberof V1PodSpec
     */
    volumes?: Array<V1Volume>;
    /**
     * WorkloadRef provides a reference to the Workload object that this Pod belongs to.
     * This field is used by the scheduler to identify the PodGroup and apply the
     * correct group scheduling policies. The Workload object referenced
     * by this field may not exist at the time the Pod is created.
     * This field is immutable, but a Workload object with the same name
     * may be recreated with different policies. Doing this during pod scheduling
     * may result in the placement not conforming to the expected policies.
     * 
     * +featureGate=GenericWorkload
     * +optional
     * @type {V1WorkloadReference}
     * @memberof V1PodSpec
     */
    workloadRef?: V1WorkloadReference;
}



/**
 * Check if a given object implements the V1PodSpec interface.
 */
export function instanceOfV1PodSpec(value: object): value is V1PodSpec {
    return true;
}

export function V1PodSpecFromJSON(json: any): V1PodSpec {
    return V1PodSpecFromJSONTyped(json, false);
}

export function V1PodSpecFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PodSpec {
    if (json == null) {
        return json;
    }
    return {
        
        'activeDeadlineSeconds': json['activeDeadlineSeconds'] == null ? undefined : json['activeDeadlineSeconds'],
        'affinity': json['affinity'] == null ? undefined : V1AffinityFromJSON(json['affinity']),
        'automountServiceAccountToken': json['automountServiceAccountToken'] == null ? undefined : json['automountServiceAccountToken'],
        'containers': json['containers'] == null ? undefined : ((json['containers'] as Array<any>).map(V1ContainerFromJSON)),
        'dnsConfig': json['dnsConfig'] == null ? undefined : V1PodDNSConfigFromJSON(json['dnsConfig']),
        'dnsPolicy': json['dnsPolicy'] == null ? undefined : V1DNSPolicyFromJSON(json['dnsPolicy']),
        'enableServiceLinks': json['enableServiceLinks'] == null ? undefined : json['enableServiceLinks'],
        'ephemeralContainers': json['ephemeralContainers'] == null ? undefined : ((json['ephemeralContainers'] as Array<any>).map(V1EphemeralContainerFromJSON)),
        'hostAliases': json['hostAliases'] == null ? undefined : ((json['hostAliases'] as Array<any>).map(V1HostAliasFromJSON)),
        'hostIPC': json['hostIPC'] == null ? undefined : json['hostIPC'],
        'hostNetwork': json['hostNetwork'] == null ? undefined : json['hostNetwork'],
        'hostPID': json['hostPID'] == null ? undefined : json['hostPID'],
        'hostUsers': json['hostUsers'] == null ? undefined : json['hostUsers'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
        'hostnameOverride': json['hostnameOverride'] == null ? undefined : json['hostnameOverride'],
        'imagePullSecrets': json['imagePullSecrets'] == null ? undefined : ((json['imagePullSecrets'] as Array<any>).map(V1LocalObjectReferenceFromJSON)),
        'initContainers': json['initContainers'] == null ? undefined : ((json['initContainers'] as Array<any>).map(V1ContainerFromJSON)),
        'nodeName': json['nodeName'] == null ? undefined : json['nodeName'],
        'nodeSelector': json['nodeSelector'] == null ? undefined : json['nodeSelector'],
        'os': json['os'] == null ? undefined : V1PodOSFromJSON(json['os']),
        'overhead': json['overhead'] == null ? undefined : (mapValues(json['overhead'], ResourceQuantityFromJSON)),
        'preemptionPolicy': json['preemptionPolicy'] == null ? undefined : V1PreemptionPolicyFromJSON(json['preemptionPolicy']),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'priorityClassName': json['priorityClassName'] == null ? undefined : json['priorityClassName'],
        'readinessGates': json['readinessGates'] == null ? undefined : ((json['readinessGates'] as Array<any>).map(V1PodReadinessGateFromJSON)),
        'resourceClaims': json['resourceClaims'] == null ? undefined : ((json['resourceClaims'] as Array<any>).map(V1PodResourceClaimFromJSON)),
        'resources': json['resources'] == null ? undefined : V1ResourceRequirementsFromJSON(json['resources']),
        'restartPolicy': json['restartPolicy'] == null ? undefined : V1RestartPolicyFromJSON(json['restartPolicy']),
        'runtimeClassName': json['runtimeClassName'] == null ? undefined : json['runtimeClassName'],
        'schedulerName': json['schedulerName'] == null ? undefined : json['schedulerName'],
        'schedulingGates': json['schedulingGates'] == null ? undefined : ((json['schedulingGates'] as Array<any>).map(V1PodSchedulingGateFromJSON)),
        'securityContext': json['securityContext'] == null ? undefined : V1PodSecurityContextFromJSON(json['securityContext']),
        'serviceAccount': json['serviceAccount'] == null ? undefined : json['serviceAccount'],
        'serviceAccountName': json['serviceAccountName'] == null ? undefined : json['serviceAccountName'],
        'setHostnameAsFQDN': json['setHostnameAsFQDN'] == null ? undefined : json['setHostnameAsFQDN'],
        'shareProcessNamespace': json['shareProcessNamespace'] == null ? undefined : json['shareProcessNamespace'],
        'subdomain': json['subdomain'] == null ? undefined : json['subdomain'],
        'terminationGracePeriodSeconds': json['terminationGracePeriodSeconds'] == null ? undefined : json['terminationGracePeriodSeconds'],
        'tolerations': json['tolerations'] == null ? undefined : ((json['tolerations'] as Array<any>).map(V1TolerationFromJSON)),
        'topologySpreadConstraints': json['topologySpreadConstraints'] == null ? undefined : ((json['topologySpreadConstraints'] as Array<any>).map(V1TopologySpreadConstraintFromJSON)),
        'volumes': json['volumes'] == null ? undefined : ((json['volumes'] as Array<any>).map(V1VolumeFromJSON)),
        'workloadRef': json['workloadRef'] == null ? undefined : V1WorkloadReferenceFromJSON(json['workloadRef']),
    };
}

export function V1PodSpecToJSON(json: any): V1PodSpec {
    return V1PodSpecToJSONTyped(json, false);
}

export function V1PodSpecToJSONTyped(value?: V1PodSpec | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeDeadlineSeconds': value['activeDeadlineSeconds'],
        'affinity': V1AffinityToJSON(value['affinity']),
        'automountServiceAccountToken': value['automountServiceAccountToken'],
        'containers': value['containers'] == null ? undefined : ((value['containers'] as Array<any>).map(V1ContainerToJSON)),
        'dnsConfig': V1PodDNSConfigToJSON(value['dnsConfig']),
        'dnsPolicy': V1DNSPolicyToJSON(value['dnsPolicy']),
        'enableServiceLinks': value['enableServiceLinks'],
        'ephemeralContainers': value['ephemeralContainers'] == null ? undefined : ((value['ephemeralContainers'] as Array<any>).map(V1EphemeralContainerToJSON)),
        'hostAliases': value['hostAliases'] == null ? undefined : ((value['hostAliases'] as Array<any>).map(V1HostAliasToJSON)),
        'hostIPC': value['hostIPC'],
        'hostNetwork': value['hostNetwork'],
        'hostPID': value['hostPID'],
        'hostUsers': value['hostUsers'],
        'hostname': value['hostname'],
        'hostnameOverride': value['hostnameOverride'],
        'imagePullSecrets': value['imagePullSecrets'] == null ? undefined : ((value['imagePullSecrets'] as Array<any>).map(V1LocalObjectReferenceToJSON)),
        'initContainers': value['initContainers'] == null ? undefined : ((value['initContainers'] as Array<any>).map(V1ContainerToJSON)),
        'nodeName': value['nodeName'],
        'nodeSelector': value['nodeSelector'],
        'os': V1PodOSToJSON(value['os']),
        'overhead': value['overhead'] == null ? undefined : (mapValues(value['overhead'], ResourceQuantityToJSON)),
        'preemptionPolicy': V1PreemptionPolicyToJSON(value['preemptionPolicy']),
        'priority': value['priority'],
        'priorityClassName': value['priorityClassName'],
        'readinessGates': value['readinessGates'] == null ? undefined : ((value['readinessGates'] as Array<any>).map(V1PodReadinessGateToJSON)),
        'resourceClaims': value['resourceClaims'] == null ? undefined : ((value['resourceClaims'] as Array<any>).map(V1PodResourceClaimToJSON)),
        'resources': V1ResourceRequirementsToJSON(value['resources']),
        'restartPolicy': V1RestartPolicyToJSON(value['restartPolicy']),
        'runtimeClassName': value['runtimeClassName'],
        'schedulerName': value['schedulerName'],
        'schedulingGates': value['schedulingGates'] == null ? undefined : ((value['schedulingGates'] as Array<any>).map(V1PodSchedulingGateToJSON)),
        'securityContext': V1PodSecurityContextToJSON(value['securityContext']),
        'serviceAccount': value['serviceAccount'],
        'serviceAccountName': value['serviceAccountName'],
        'setHostnameAsFQDN': value['setHostnameAsFQDN'],
        'shareProcessNamespace': value['shareProcessNamespace'],
        'subdomain': value['subdomain'],
        'terminationGracePeriodSeconds': value['terminationGracePeriodSeconds'],
        'tolerations': value['tolerations'] == null ? undefined : ((value['tolerations'] as Array<any>).map(V1TolerationToJSON)),
        'topologySpreadConstraints': value['topologySpreadConstraints'] == null ? undefined : ((value['topologySpreadConstraints'] as Array<any>).map(V1TopologySpreadConstraintToJSON)),
        'volumes': value['volumes'] == null ? undefined : ((value['volumes'] as Array<any>).map(V1VolumeToJSON)),
        'workloadRef': V1WorkloadReferenceToJSON(value['workloadRef']),
    };
}

