/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1PodResourceClaim
 */
export interface V1PodResourceClaim {
    /**
     * Name uniquely identifies this resource claim inside the pod.
     * This must be a DNS_LABEL.
     * @type {string}
     * @memberof V1PodResourceClaim
     */
    name?: string;
    /**
     * ResourceClaimName is the name of a ResourceClaim object in the same
     * namespace as this pod.
     * 
     * Exactly one of ResourceClaimName and ResourceClaimTemplateName must
     * be set.
     * @type {string}
     * @memberof V1PodResourceClaim
     */
    resourceClaimName?: string;
    /**
     * ResourceClaimTemplateName is the name of a ResourceClaimTemplate
     * object in the same namespace as this pod.
     * 
     * The template will be used to create a new ResourceClaim, which will
     * be bound to this pod. When this pod is deleted, the ResourceClaim
     * will also be deleted. The pod name and resource name, along with a
     * generated component, will be used to form a unique name for the
     * ResourceClaim, which will be recorded in pod.status.resourceClaimStatuses.
     * 
     * This field is immutable and no changes will be made to the
     * corresponding ResourceClaim by the control plane after creating the
     * ResourceClaim.
     * 
     * Exactly one of ResourceClaimName and ResourceClaimTemplateName must
     * be set.
     * @type {string}
     * @memberof V1PodResourceClaim
     */
    resourceClaimTemplateName?: string;
}

/**
 * Check if a given object implements the V1PodResourceClaim interface.
 */
export function instanceOfV1PodResourceClaim(value: object): value is V1PodResourceClaim {
    return true;
}

export function V1PodResourceClaimFromJSON(json: any): V1PodResourceClaim {
    return V1PodResourceClaimFromJSONTyped(json, false);
}

export function V1PodResourceClaimFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1PodResourceClaim {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'resourceClaimName': json['resourceClaimName'] == null ? undefined : json['resourceClaimName'],
        'resourceClaimTemplateName': json['resourceClaimTemplateName'] == null ? undefined : json['resourceClaimTemplateName'],
    };
}

export function V1PodResourceClaimToJSON(json: any): V1PodResourceClaim {
    return V1PodResourceClaimToJSONTyped(json, false);
}

export function V1PodResourceClaimToJSONTyped(value?: V1PodResourceClaim | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'resourceClaimName': value['resourceClaimName'],
        'resourceClaimTemplateName': value['resourceClaimTemplateName'],
    };
}

