/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1LocalObjectReference } from './V1LocalObjectReference';
import {
    V1LocalObjectReferenceFromJSON,
    V1LocalObjectReferenceFromJSONTyped,
    V1LocalObjectReferenceToJSON,
    V1LocalObjectReferenceToJSONTyped,
} from './V1LocalObjectReference';

/**
 * 
 * @export
 * @interface V1RBDVolumeSource
 */
export interface V1RBDVolumeSource {
    /**
     * fsType is the filesystem type of the volume that you want to mount.
     * Tip: Ensure that the filesystem type is supported by the host operating system.
     * Examples: "ext4", "xfs", "ntfs". Implicitly inferred to be "ext4" if unspecified.
     * More info: https://kubernetes.io/docs/concepts/storage/volumes#rbd
     * TODO: how do we prevent errors in the filesystem from compromising the machine
     * +optional
     * @type {string}
     * @memberof V1RBDVolumeSource
     */
    fsType?: string;
    /**
     * image is the rados image name.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * @type {string}
     * @memberof V1RBDVolumeSource
     */
    image?: string;
    /**
     * keyring is the path to key ring for RBDUser.
     * Default is /etc/ceph/keyring.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +optional
     * +default="/etc/ceph/keyring"
     * @type {string}
     * @memberof V1RBDVolumeSource
     */
    keyring?: string;
    /**
     * monitors is a collection of Ceph monitors.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +listType=atomic
     * @type {Array<string>}
     * @memberof V1RBDVolumeSource
     */
    monitors?: Array<string>;
    /**
     * pool is the rados pool name.
     * Default is rbd.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +optional
     * +default="rbd"
     * @type {string}
     * @memberof V1RBDVolumeSource
     */
    pool?: string;
    /**
     * readOnly here will force the ReadOnly setting in VolumeMounts.
     * Defaults to false.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +optional
     * @type {boolean}
     * @memberof V1RBDVolumeSource
     */
    readOnly?: boolean;
    /**
     * secretRef is name of the authentication secret for RBDUser. If provided
     * overrides keyring.
     * Default is nil.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +optional
     * @type {V1LocalObjectReference}
     * @memberof V1RBDVolumeSource
     */
    secretRef?: V1LocalObjectReference;
    /**
     * user is the rados user name.
     * Default is admin.
     * More info: https://examples.k8s.io/volumes/rbd/README.md#how-to-use-it
     * +optional
     * +default="admin"
     * @type {string}
     * @memberof V1RBDVolumeSource
     */
    user?: string;
}

/**
 * Check if a given object implements the V1RBDVolumeSource interface.
 */
export function instanceOfV1RBDVolumeSource(value: object): value is V1RBDVolumeSource {
    return true;
}

export function V1RBDVolumeSourceFromJSON(json: any): V1RBDVolumeSource {
    return V1RBDVolumeSourceFromJSONTyped(json, false);
}

export function V1RBDVolumeSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1RBDVolumeSource {
    if (json == null) {
        return json;
    }
    return {
        
        'fsType': json['fsType'] == null ? undefined : json['fsType'],
        'image': json['image'] == null ? undefined : json['image'],
        'keyring': json['keyring'] == null ? undefined : json['keyring'],
        'monitors': json['monitors'] == null ? undefined : json['monitors'],
        'pool': json['pool'] == null ? undefined : json['pool'],
        'readOnly': json['readOnly'] == null ? undefined : json['readOnly'],
        'secretRef': json['secretRef'] == null ? undefined : V1LocalObjectReferenceFromJSON(json['secretRef']),
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function V1RBDVolumeSourceToJSON(json: any): V1RBDVolumeSource {
    return V1RBDVolumeSourceToJSONTyped(json, false);
}

export function V1RBDVolumeSourceToJSONTyped(value?: V1RBDVolumeSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fsType': value['fsType'],
        'image': value['image'],
        'keyring': value['keyring'],
        'monitors': value['monitors'],
        'pool': value['pool'],
        'readOnly': value['readOnly'],
        'secretRef': V1LocalObjectReferenceToJSON(value['secretRef']),
        'user': value['user'],
    };
}

