/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1ResourceResizeRestartPolicy = {
    NotRequired: 'NotRequired',
    RestartContainer: 'RestartContainer'
} as const;
export type V1ResourceResizeRestartPolicy = typeof V1ResourceResizeRestartPolicy[keyof typeof V1ResourceResizeRestartPolicy];


export function instanceOfV1ResourceResizeRestartPolicy(value: any): boolean {
    for (const key in V1ResourceResizeRestartPolicy) {
        if (Object.prototype.hasOwnProperty.call(V1ResourceResizeRestartPolicy, key)) {
            if (V1ResourceResizeRestartPolicy[key as keyof typeof V1ResourceResizeRestartPolicy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1ResourceResizeRestartPolicyFromJSON(json: any): V1ResourceResizeRestartPolicy {
    return V1ResourceResizeRestartPolicyFromJSONTyped(json, false);
}

export function V1ResourceResizeRestartPolicyFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ResourceResizeRestartPolicy {
    return json as V1ResourceResizeRestartPolicy;
}

export function V1ResourceResizeRestartPolicyToJSON(value?: V1ResourceResizeRestartPolicy | null): any {
    return value as any;
}

export function V1ResourceResizeRestartPolicyToJSONTyped(value: any, ignoreDiscriminator: boolean): V1ResourceResizeRestartPolicy {
    return value as V1ResourceResizeRestartPolicy;
}

