/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SELinuxOptions
 */
export interface V1SELinuxOptions {
    /**
     * Level is SELinux level label that applies to the container.
     * +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    level?: string;
    /**
     * Role is a SELinux role label that applies to the container.
     * +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    role?: string;
    /**
     * Type is a SELinux type label that applies to the container.
     * +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    type?: string;
    /**
     * User is a SELinux user label that applies to the container.
     * +optional
     * @type {string}
     * @memberof V1SELinuxOptions
     */
    user?: string;
}

/**
 * Check if a given object implements the V1SELinuxOptions interface.
 */
export function instanceOfV1SELinuxOptions(value: object): value is V1SELinuxOptions {
    return true;
}

export function V1SELinuxOptionsFromJSON(json: any): V1SELinuxOptions {
    return V1SELinuxOptionsFromJSONTyped(json, false);
}

export function V1SELinuxOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SELinuxOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'level': json['level'] == null ? undefined : json['level'],
        'role': json['role'] == null ? undefined : json['role'],
        'type': json['type'] == null ? undefined : json['type'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function V1SELinuxOptionsToJSON(json: any): V1SELinuxOptions {
    return V1SELinuxOptionsToJSONTyped(json, false);
}

export function V1SELinuxOptionsToJSONTyped(value?: V1SELinuxOptions | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'level': value['level'],
        'role': value['role'],
        'type': value['type'],
        'user': value['user'],
    };
}

