/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SeccompProfileType } from './V1SeccompProfileType';
import {
    V1SeccompProfileTypeFromJSON,
    V1SeccompProfileTypeFromJSONTyped,
    V1SeccompProfileTypeToJSON,
    V1SeccompProfileTypeToJSONTyped,
} from './V1SeccompProfileType';

/**
 * 
 * @export
 * @interface V1SeccompProfile
 */
export interface V1SeccompProfile {
    /**
     * localhostProfile indicates a profile defined in a file on the node should be used.
     * The profile must be preconfigured on the node to work.
     * Must be a descending path, relative to the kubelet's configured seccomp profile location.
     * Must be set if type is "Localhost". Must NOT be set for any other type.
     * +optional
     * @type {string}
     * @memberof V1SeccompProfile
     */
    localhostProfile?: string;
    /**
     * type indicates which kind of seccomp profile will be applied.
     * Valid options are:
     * 
     * Localhost - a profile defined in a file on the node should be used.
     * RuntimeDefault - the container runtime default profile should be used.
     * Unconfined - no profile should be applied.
     * +unionDiscriminator
     * @type {V1SeccompProfileType}
     * @memberof V1SeccompProfile
     */
    type?: V1SeccompProfileType;
}



/**
 * Check if a given object implements the V1SeccompProfile interface.
 */
export function instanceOfV1SeccompProfile(value: object): value is V1SeccompProfile {
    return true;
}

export function V1SeccompProfileFromJSON(json: any): V1SeccompProfile {
    return V1SeccompProfileFromJSONTyped(json, false);
}

export function V1SeccompProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SeccompProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'localhostProfile': json['localhostProfile'] == null ? undefined : json['localhostProfile'],
        'type': json['type'] == null ? undefined : V1SeccompProfileTypeFromJSON(json['type']),
    };
}

export function V1SeccompProfileToJSON(json: any): V1SeccompProfile {
    return V1SeccompProfileToJSONTyped(json, false);
}

export function V1SeccompProfileToJSONTyped(value?: V1SeccompProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'localhostProfile': value['localhostProfile'],
        'type': V1SeccompProfileTypeToJSON(value['type']),
    };
}

