/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V1SELinuxOptions } from './V1SELinuxOptions';
import {
    V1SELinuxOptionsFromJSON,
    V1SELinuxOptionsFromJSONTyped,
    V1SELinuxOptionsToJSON,
    V1SELinuxOptionsToJSONTyped,
} from './V1SELinuxOptions';
import type { V1ProcMountType } from './V1ProcMountType';
import {
    V1ProcMountTypeFromJSON,
    V1ProcMountTypeFromJSONTyped,
    V1ProcMountTypeToJSON,
    V1ProcMountTypeToJSONTyped,
} from './V1ProcMountType';
import type { V1Capabilities } from './V1Capabilities';
import {
    V1CapabilitiesFromJSON,
    V1CapabilitiesFromJSONTyped,
    V1CapabilitiesToJSON,
    V1CapabilitiesToJSONTyped,
} from './V1Capabilities';
import type { V1SeccompProfile } from './V1SeccompProfile';
import {
    V1SeccompProfileFromJSON,
    V1SeccompProfileFromJSONTyped,
    V1SeccompProfileToJSON,
    V1SeccompProfileToJSONTyped,
} from './V1SeccompProfile';
import type { V1WindowsSecurityContextOptions } from './V1WindowsSecurityContextOptions';
import {
    V1WindowsSecurityContextOptionsFromJSON,
    V1WindowsSecurityContextOptionsFromJSONTyped,
    V1WindowsSecurityContextOptionsToJSON,
    V1WindowsSecurityContextOptionsToJSONTyped,
} from './V1WindowsSecurityContextOptions';
import type { V1AppArmorProfile } from './V1AppArmorProfile';
import {
    V1AppArmorProfileFromJSON,
    V1AppArmorProfileFromJSONTyped,
    V1AppArmorProfileToJSON,
    V1AppArmorProfileToJSONTyped,
} from './V1AppArmorProfile';

/**
 * 
 * @export
 * @interface V1SecurityContext
 */
export interface V1SecurityContext {
    /**
     * AllowPrivilegeEscalation controls whether a process can gain more
     * privileges than its parent process. This bool directly controls if
     * the no_new_privs flag will be set on the container process.
     * AllowPrivilegeEscalation is true always when the container is:
     * 1) run as Privileged
     * 2) has CAP_SYS_ADMIN
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {boolean}
     * @memberof V1SecurityContext
     */
    allowPrivilegeEscalation?: boolean;
    /**
     * appArmorProfile is the AppArmor options to use by this container. If set, this profile
     * overrides the pod's appArmorProfile.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {V1AppArmorProfile}
     * @memberof V1SecurityContext
     */
    appArmorProfile?: V1AppArmorProfile;
    /**
     * The capabilities to add/drop when running containers.
     * Defaults to the default set of capabilities granted by the container runtime.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {V1Capabilities}
     * @memberof V1SecurityContext
     */
    capabilities?: V1Capabilities;
    /**
     * Run container in privileged mode.
     * Processes in privileged containers are essentially equivalent to root on the host.
     * Defaults to false.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {boolean}
     * @memberof V1SecurityContext
     */
    privileged?: boolean;
    /**
     * procMount denotes the type of proc mount to use for the containers.
     * The default value is Default which uses the container runtime defaults for
     * readonly paths and masked paths.
     * This requires the ProcMountType feature flag to be enabled.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {V1ProcMountType}
     * @memberof V1SecurityContext
     */
    procMount?: V1ProcMountType;
    /**
     * Whether this container has a read-only root filesystem.
     * Default is false.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {boolean}
     * @memberof V1SecurityContext
     */
    readOnlyRootFilesystem?: boolean;
    /**
     * The GID to run the entrypoint of the container process.
     * Uses runtime default if unset.
     * May also be set in PodSecurityContext.  If set in both SecurityContext and
     * PodSecurityContext, the value specified in SecurityContext takes precedence.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {number}
     * @memberof V1SecurityContext
     */
    runAsGroup?: number;
    /**
     * Indicates that the container must run as a non-root user.
     * If true, the Kubelet will validate the image at runtime to ensure that it
     * does not run as UID 0 (root) and fail to start the container if it does.
     * If unset or false, no such validation will be performed.
     * May also be set in PodSecurityContext.  If set in both SecurityContext and
     * PodSecurityContext, the value specified in SecurityContext takes precedence.
     * +optional
     * @type {boolean}
     * @memberof V1SecurityContext
     */
    runAsNonRoot?: boolean;
    /**
     * The UID to run the entrypoint of the container process.
     * Defaults to user specified in image metadata if unspecified.
     * May also be set in PodSecurityContext.  If set in both SecurityContext and
     * PodSecurityContext, the value specified in SecurityContext takes precedence.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {number}
     * @memberof V1SecurityContext
     */
    runAsUser?: number;
    /**
     * The SELinux context to be applied to the container.
     * If unspecified, the container runtime will allocate a random SELinux context for each
     * container.  May also be set in PodSecurityContext.  If set in both SecurityContext and
     * PodSecurityContext, the value specified in SecurityContext takes precedence.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {V1SELinuxOptions}
     * @memberof V1SecurityContext
     */
    seLinuxOptions?: V1SELinuxOptions;
    /**
     * The seccomp options to use by this container. If seccomp options are
     * provided at both the pod & container level, the container options
     * override the pod options.
     * Note that this field cannot be set when spec.os.name is windows.
     * +optional
     * @type {V1SeccompProfile}
     * @memberof V1SecurityContext
     */
    seccompProfile?: V1SeccompProfile;
    /**
     * The Windows specific settings applied to all containers.
     * If unspecified, the options from the PodSecurityContext will be used.
     * If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.
     * Note that this field cannot be set when spec.os.name is linux.
     * +optional
     * @type {V1WindowsSecurityContextOptions}
     * @memberof V1SecurityContext
     */
    windowsOptions?: V1WindowsSecurityContextOptions;
}



/**
 * Check if a given object implements the V1SecurityContext interface.
 */
export function instanceOfV1SecurityContext(value: object): value is V1SecurityContext {
    return true;
}

export function V1SecurityContextFromJSON(json: any): V1SecurityContext {
    return V1SecurityContextFromJSONTyped(json, false);
}

export function V1SecurityContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SecurityContext {
    if (json == null) {
        return json;
    }
    return {
        
        'allowPrivilegeEscalation': json['allowPrivilegeEscalation'] == null ? undefined : json['allowPrivilegeEscalation'],
        'appArmorProfile': json['appArmorProfile'] == null ? undefined : V1AppArmorProfileFromJSON(json['appArmorProfile']),
        'capabilities': json['capabilities'] == null ? undefined : V1CapabilitiesFromJSON(json['capabilities']),
        'privileged': json['privileged'] == null ? undefined : json['privileged'],
        'procMount': json['procMount'] == null ? undefined : V1ProcMountTypeFromJSON(json['procMount']),
        'readOnlyRootFilesystem': json['readOnlyRootFilesystem'] == null ? undefined : json['readOnlyRootFilesystem'],
        'runAsGroup': json['runAsGroup'] == null ? undefined : json['runAsGroup'],
        'runAsNonRoot': json['runAsNonRoot'] == null ? undefined : json['runAsNonRoot'],
        'runAsUser': json['runAsUser'] == null ? undefined : json['runAsUser'],
        'seLinuxOptions': json['seLinuxOptions'] == null ? undefined : V1SELinuxOptionsFromJSON(json['seLinuxOptions']),
        'seccompProfile': json['seccompProfile'] == null ? undefined : V1SeccompProfileFromJSON(json['seccompProfile']),
        'windowsOptions': json['windowsOptions'] == null ? undefined : V1WindowsSecurityContextOptionsFromJSON(json['windowsOptions']),
    };
}

export function V1SecurityContextToJSON(json: any): V1SecurityContext {
    return V1SecurityContextToJSONTyped(json, false);
}

export function V1SecurityContextToJSONTyped(value?: V1SecurityContext | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowPrivilegeEscalation': value['allowPrivilegeEscalation'],
        'appArmorProfile': V1AppArmorProfileToJSON(value['appArmorProfile']),
        'capabilities': V1CapabilitiesToJSON(value['capabilities']),
        'privileged': value['privileged'],
        'procMount': V1ProcMountTypeToJSON(value['procMount']),
        'readOnlyRootFilesystem': value['readOnlyRootFilesystem'],
        'runAsGroup': value['runAsGroup'],
        'runAsNonRoot': value['runAsNonRoot'],
        'runAsUser': value['runAsUser'],
        'seLinuxOptions': V1SELinuxOptionsToJSON(value['seLinuxOptions']),
        'seccompProfile': V1SeccompProfileToJSON(value['seccompProfile']),
        'windowsOptions': V1WindowsSecurityContextOptionsToJSON(value['windowsOptions']),
    };
}

