/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SecretEnvSource
 */
export interface V1SecretEnvSource {
    /**
     * Name of the referent.
     * This field is effectively required, but due to backwards compatibility is
     * allowed to be empty. Instances of this type with an empty value here are
     * almost certainly wrong.
     * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
     * +optional
     * +default=""
     * +kubebuilder:default=""
     * TODO: Drop `kubebuilder:default` when controller-gen doesn't need it https://github.com/kubernetes-sigs/kubebuilder/issues/3896.
     * @type {string}
     * @memberof V1SecretEnvSource
     */
    name?: string;
    /**
     * Specify whether the Secret must be defined
     * +optional
     * @type {boolean}
     * @memberof V1SecretEnvSource
     */
    optional?: boolean;
}

/**
 * Check if a given object implements the V1SecretEnvSource interface.
 */
export function instanceOfV1SecretEnvSource(value: object): value is V1SecretEnvSource {
    return true;
}

export function V1SecretEnvSourceFromJSON(json: any): V1SecretEnvSource {
    return V1SecretEnvSourceFromJSONTyped(json, false);
}

export function V1SecretEnvSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SecretEnvSource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'optional': json['optional'] == null ? undefined : json['optional'],
    };
}

export function V1SecretEnvSourceToJSON(json: any): V1SecretEnvSource {
    return V1SecretEnvSourceToJSONTyped(json, false);
}

export function V1SecretEnvSourceToJSONTyped(value?: V1SecretEnvSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'optional': value['optional'],
    };
}

