/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1SleepAction
 */
export interface V1SleepAction {
    /**
     * Seconds is the number of seconds to sleep.
     * @type {number}
     * @memberof V1SleepAction
     */
    seconds?: number;
}

/**
 * Check if a given object implements the V1SleepAction interface.
 */
export function instanceOfV1SleepAction(value: object): value is V1SleepAction {
    return true;
}

export function V1SleepActionFromJSON(json: any): V1SleepAction {
    return V1SleepActionFromJSONTyped(json, false);
}

export function V1SleepActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1SleepAction {
    if (json == null) {
        return json;
    }
    return {
        
        'seconds': json['seconds'] == null ? undefined : json['seconds'],
    };
}

export function V1SleepActionToJSON(json: any): V1SleepAction {
    return V1SleepActionToJSONTyped(json, false);
}

export function V1SleepActionToJSONTyped(value?: V1SleepAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'seconds': value['seconds'],
    };
}

