/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const V1TolerationOperator = {
    TolerationOpExists: 'Exists',
    TolerationOpEqual: 'Equal',
    TolerationOpLt: 'Lt',
    TolerationOpGt: 'Gt'
} as const;
export type V1TolerationOperator = typeof V1TolerationOperator[keyof typeof V1TolerationOperator];


export function instanceOfV1TolerationOperator(value: any): boolean {
    for (const key in V1TolerationOperator) {
        if (Object.prototype.hasOwnProperty.call(V1TolerationOperator, key)) {
            if (V1TolerationOperator[key as keyof typeof V1TolerationOperator] === value) {
                return true;
            }
        }
    }
    return false;
}

export function V1TolerationOperatorFromJSON(json: any): V1TolerationOperator {
    return V1TolerationOperatorFromJSONTyped(json, false);
}

export function V1TolerationOperatorFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1TolerationOperator {
    return json as V1TolerationOperator;
}

export function V1TolerationOperatorToJSON(value?: V1TolerationOperator | null): any {
    return value as any;
}

export function V1TolerationOperatorToJSONTyped(value: any, ignoreDiscriminator: boolean): V1TolerationOperator {
    return value as V1TolerationOperator;
}

