/* tslint:disable */
/* eslint-disable */
/**
 * komputer.ai API
 * API-first platform for running persistent Claude AI agents on Kubernetes. Designed to be driven by external systems — create agents, send tasks, and stream real-time results via REST + WebSocket.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1WorkloadReference
 */
export interface V1WorkloadReference {
    /**
     * Name defines the name of the Workload object this Pod belongs to.
     * Workload must be in the same namespace as the Pod.
     * If it doesn't match any existing Workload, the Pod will remain unschedulable
     * until a Workload object is created and observed by the kube-scheduler.
     * It must be a DNS subdo
     * 
     * +required
     * @type {string}
     * @memberof V1WorkloadReference
     */
    name?: string;
    /**
     * PodGroup is the name of the PodGroup within the Workload that this Pod
     * belongs to. If it doesn't match any existing PodGroup within the Workload,
     * the Pod will remain unschedulable until the Workload object is recreated
     * and observed by the kube-scheduler. It must be a DNS label.
     * 
     * +required
     * @type {string}
     * @memberof V1WorkloadReference
     */
    podGroup?: string;
    /**
     * PodGroupReplicaKey specifies the replica key of the PodGroup to which this
     * Pod belongs. It is used to distinguish pods belonging to different replicas
     * of the same pod group. The pod group policy is applied separately to each replica.
     * When set, it must be a DNS label.
     * 
     * +optional
     * @type {string}
     * @memberof V1WorkloadReference
     */
    podGroupReplicaKey?: string;
}

/**
 * Check if a given object implements the V1WorkloadReference interface.
 */
export function instanceOfV1WorkloadReference(value: object): value is V1WorkloadReference {
    return true;
}

export function V1WorkloadReferenceFromJSON(json: any): V1WorkloadReference {
    return V1WorkloadReferenceFromJSONTyped(json, false);
}

export function V1WorkloadReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1WorkloadReference {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'podGroup': json['podGroup'] == null ? undefined : json['podGroup'],
        'podGroupReplicaKey': json['podGroupReplicaKey'] == null ? undefined : json['podGroupReplicaKey'],
    };
}

export function V1WorkloadReferenceToJSON(json: any): V1WorkloadReference {
    return V1WorkloadReferenceToJSONTyped(json, false);
}

export function V1WorkloadReferenceToJSONTyped(value?: V1WorkloadReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'podGroup': value['podGroup'],
        'podGroupReplicaKey': value['podGroupReplicaKey'],
    };
}

