---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents
  - komputeragenttemplates
  - komputerredisconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/finalizers
  - komputeragenttemplates/finalizers
  - komputerredisconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/status
  - komputeragenttemplates/status
  - komputerredisconfigs/status
  verbs:
  - get
  - patch
  - update
