---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragentclustertemplates
  - komputeragenttemplates
  - komputerconfigs
  - komputermemories
  - komputerskills
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents
  - komputeroffices
  - komputerschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/finalizers
  - komputeroffices/finalizers
  - komputerschedules/finalizers
  verbs:
  - update
- apiGroups:
  - komputer.komputer.ai
  resources:
  - komputeragents/status
  - komputermemories/status
  - komputeroffices/status
  - komputerschedules/status
  - komputerskills/status
  verbs:
  - get
  - patch
  - update
